(()=>{'use strict';
const $=id=>document.getElementById(id);
const DATA='https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator/main/';
const TILES='https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/maps/tiles/';
const SIZE=16384;
let map=null,mapData=null,gun=null,target=null,towerLayer=null,facilityLayer=null,battleLayer=null,gridLayer=null,gunLayer=null,targetLayer=null,routeLayer=null;
const toast=s=>{const e=$('toast');if(e){e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1300)}};
const zh=()=>($('lang')?.textContent==='EN');
const label=s=>zh()?String(s).replace(/^Tower /,'高塔 ').replace('Weapons Vendor','武器商人').replace('Garage Vendor','车库商人').replace('Spawn Board','复活板'):s;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const mode=()=>($('setTarget')?.classList.contains('active')?'target':'gun');
const locked=k=>{const b=$(k==='gun'?'lockGun':'lockTarget');return b?(/UNLOCK|解锁/.test(b.textContent)):false};
const setCoords=()=>{if(gun){$('sx').value=gun.x.toFixed(2);$('sy').value=gun.y.toFixed(2);$('gunCoord').textContent=gun.x.toFixed(2)+', '+gun.y.toFixed(2)}else{$('sx').value='';$('sy').value='';$('gunCoord').textContent='--'}if(target){$('tx').value=target.x.toFixed(2);$('ty').value=target.y.toFixed(2);$('targetCoord').textContent=target.x.toFixed(2)+', '+target.y.toFixed(2)}else{$('tx').value='';$('ty').value='';$('targetCoord').textContent='--'}if($('sx'))$('sx').disabled=locked('gun');if($('sy'))$('sy').disabled=locked('gun');if($('tx'))$('tx').disabled=locked('target');if($('ty'))$('ty').disabled=locked('target');syncMarkers()};
const readInputs=()=>{let sx=parseFloat($('sx').value),sy=parseFloat($('sy').value),tx=parseFloat($('tx').value),ty=parseFloat($('ty').value);if(!locked('gun')&&Number.isFinite(sx)&&Number.isFinite(sy))gun={x:sx,y:sy};if(!locked('target')&&Number.isFinite(tx)&&Number.isFinite(ty))target={x:tx,y:ty};syncMarkers();focusPoints()};
const gameLL=c=>[1-c.y/163.84,c.x/163.84];
function syncMarkers(){if(!map)return;gunLayer=gunLayer||L.layerGroup().addTo(map);targetLayer=targetLayer||L.layerGroup().addTo(map);gunLayer.clearLayers();targetLayer.clearLayers();const z=Math.max(.45,Math.min(1,1/Math.sqrt((map.getZoom()||1)+.35)));if(gun)gunLayer.addLayer(L.marker(gameLL(gun),{interactive:false,icon:L.divIcon({className:'point-gun',html:'<i></i>',iconSize:[26*z,26*z],iconAnchor:[13*z,13*z]})}));if(target)targetLayer.addLayer(L.marker(gameLL(target),{interactive:false,icon:L.divIcon({className:'point-target',html:'<i></i>',iconSize:[26*z,26*z],iconAnchor:[13*z,13*z]})}));if(routeLayer){routeLayer.remove();routeLayer=null}if(gun&&target)routeLayer=L.polyline([gameLL(gun),gameLL(target)],{color:'#ffd65a',weight:1.5,dashArray:'6 5',opacity:.85,interactive:false}).addTo(map)}
function towerIcon(m){return L.divIcon({className:'wardogs-tower-marker',html:'<img src="https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/assets/map-markers/tower.webp" alt=""><span class="wardogs-label">'+esc(label(m.label))+'</span>',iconSize:[30,42],iconAnchor:[15,21]})}
function poiIcon(m){let name=m.icon==='spawn_board'?'spawn_board':m.icon==='weapons_vendor'?'weapons_vendor':m.icon==='garage_vendor'?'garage_vendor':m.icon;return L.divIcon({className:'wardogs-poi-marker',html:'<img src="https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/assets/map-markers/'+encodeURIComponent(name)+'.webp" onerror="this.style.display=\'none\'" alt=""><span class="wardogs-label">'+esc(label(m.label))+'</span>',iconSize:[26,38],iconAnchor:[13,19]})}
function currentMarkerSize(base=1){const z=map?.getZoom()||1;return Math.max(.36,Math.min(1,base/Math.sqrt(z+.2)))}
function addMarkerScaled(layer,m,isTower){const k=currentMarkerSize(isTower?1:0.85),ic=isTower?L.divIcon({className:'wardogs-tower-marker',html:'<img src="https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/assets/map-markers/tower.webp" alt=""><span class="wardogs-label">'+esc(label(m.label))+'</span>',iconSize:[32*k,46*k],iconAnchor:[16*k,23*k]}):L.divIcon({className:'wardogs-poi-marker',html:'<img src="https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/assets/map-markers/'+encodeURIComponent(m.icon)+'.webp" onerror="this.style.display=\'none\'" alt=""><span class="wardogs-label">'+esc(label(m.label))+'</span>',iconSize:[28*k,40*k],iconAnchor:[14*k,20*k]});const mk=L.marker([1-m.y/SIZE,m.x/SIZE],{icon:ic,keyboard:false});if(isTower)mk.on('click',e=>{L.DomEvent.stopPropagation(e);setTower(m.label)});layer.addLayer(mk)}
function refreshLayers(){if(!map||!mapData)return;[towerLayer,facilityLayer,battleLayer,gridLayer].forEach(l=>l?.clearLayers());if($('towerLayer')?.checked!==false)(mapData.markers||[]).filter(m=>m.icon==='tower').forEach(m=>addMarkerScaled(towerLayer,m,true));if($('facilityLayer')?.checked!==false)(mapData.markers||[]).filter(m=>m.icon!=='tower').forEach(m=>addMarkerScaled(facilityLayer,m,false));if($('battleLayer')?.checked!==false)(mapData.polygons||[]).forEach(p=>battleLayer.addLayer(L.polygon((p.points||[]).map(q=>[1-q.y/SIZE,q.x/SIZE]),{color:p.color||'#6fa9ce',weight:2,dashArray:'7 5',fillOpacity:p.fillOpacity??.12,interactive:false})));if($('gridLayer')?.checked!==false)for(let i=0;i<=16;i++){let p=i/16;gridLayer.addLayer(L.polyline([[p,0],[p,1]],{color:'#65a9df',weight:1,opacity:.15,interactive:false}));gridLayer.addLayer(L.polyline([[0,p],[1,p]],{color:'#65a9df',weight:1,opacity:.15,interactive:false}))}syncMarkers();fillQuick()}
function syncMapToPage(){setCoords();$('calc')?.click()}
function setTower(name){if(!name||!mapData)return;const m=(mapData.markers||[]).find(x=>x.icon==='tower'&&x.label===name);if(!m)return;const c={x:m.x/100,y:(SIZE-m.y)/100};if(mode()==='gun'){if(locked('gun'))return toast(zh()?'炮位已锁定':'Gun is locked');gun=c}else{if(locked('target'))return toast(zh()?'目标已锁定':'Target is locked');target=c}syncMapToPage();map.setView(gameLL(c),5,{animate:false});toast(label(name))}
function fillQuick(){if(!$('towerQuick')){const d=document.createElement('div');d.id='towerQuick';d.className='towerQuick';d.innerHTML='<div id="towerQuickTitle" class="qt"></div><select id="towerSelect"><option value=""></option></select><button id="towerGo"></button>';$('map').parentElement.insertBefore(d,$('map'));$('towerGo').onclick=()=>setTower($('towerSelect').value)}if(!$('towerSelect'))return;$('towerQuickTitle').textContent=zh()?'高塔快速定位':'TOWER QUICK LOCATION';$('towerGo').textContent=zh()?'定位':'GO';$('towerSelect').innerHTML='<option value="">'+(zh()?'选择高塔':'SELECT TOWER')+'</option>';(mapData?.markers||[]).filter(m=>m.icon==='tower').sort((a,b)=>a.label.localeCompare(b.label,undefined,{numeric:true})).forEach(m=>{const o=document.createElement('option');o.value=m.label;o.textContent=label(m.label);$('towerSelect').appendChild(o)})}
function focusPoints(){if(!map)return;if(gun&&target)map.fitBounds(L.latLngBounds(gameLL(gun),gameLL(target)),{padding:[45,45],maxZoom:5,animate:false});else if(gun)map.setView(gameLL(gun),5,{animate:false});else if(target)map.setView(gameLL(target),5,{animate:false})}
async function loadConfig(id){try{const r=await fetch(DATA+'maps/'+id+'.json',{cache:'force-cache'});if(r.ok)mapData=await r.json();else throw 0}catch{mapData={markers:[],polygons:[]}}}
async function setTiles(id){if(!map)return;map.eachLayer(l=>{if(l instanceof L.TileLayer)map.removeLayer(l)});L.tileLayer(TILES+id+'/zoom_{z}/{x}_{y}.webp',{minZoom:0,maxZoom:7,maxNativeZoom:7,tileSize:256,noWrap:true,keepBuffer:1,reuseTiles:true,updateWhenIdle:true,updateWhenZooming:false,fadeAnimation:false,detectRetina:false,attribution:'WARDOGS community map'}).addTo(map);await loadConfig(id);refreshLayers();readInputs();setTimeout(()=>{map.invalidateSize(false);focusPoints()},40)}
async function initMap(){if(map){map.invalidateSize(false);readInputs();focusPoints();return}const link=document.createElement('link');link.rel='stylesheet';link.href='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(link);await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)});mapCss();map=L.map('map',{crs:L.CRS.Simple,minZoom:0,maxZoom:7,zoomDelta:.5,zoomSnap:.5,zoomControl:true,attributionControl:true,inertia:true,zoomAnimation:true,fadeAnimation:false,markerZoomAnimation:true,tap:false});map.setView([.5,.5],0,{animate:false});towerLayer=L.layerGroup().addTo(map);facilityLayer=L.layerGroup().addTo(map);battleLayer=L.layerGroup().addTo(map);gridLayer=L.layerGroup().addTo(map);gunLayer=L.layerGroup().addTo(map);targetLayer=L.layerGroup().addTo(map);map.on('click',e=>{const c=fromMap(e.latlng);if(mode()==='gun'){if(locked('gun'))return toast(zh()?'炮位已锁定':'Gun is locked');gun=c}else{if(locked('target'))return toast(zh()?'目标已锁定':'Target is locked');target=c}syncMapToPage()});map.on('zoomend',()=>{refreshLayers();syncMarkers()});await setTiles($('mapSelect')?.value||'bakurani')}
function fromMap(ll){return{x:ll.lng*163.84,y:(1-ll.lat)*163.84}}
function mapCss(){if($('mapv10css'))return;const s=document.createElement('style');s.id='mapv10css';s.textContent='.towerQuick{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;background:linear-gradient(#131e28,#091117);border:1px solid #304657;border-radius:12px;padding:9px;margin:8px 0}.towerQuick .qt{font:900 10px ui-monospace,monospace;color:#9badbf;white-space:nowrap}.towerQuick select{width:100%;min-width:0}.towerQuick button{background:linear-gradient(#4b9cff,#296fd0);border:1px solid #6ab1ff;color:#fff}.wardogs-tower-marker,.wardogs-poi-marker{background:transparent;border:0}.wardogs-tower-marker img,.wardogs-poi-marker img{width:100%;height:100%;object-fit:contain;display:block;filter:drop-shadow(0 2px 3px #000)}.wardogs-label{display:block;background:#03070de5;border:1px solid #304552;color:#eef4f9;border-radius:4px;padding:2px 4px;margin-top:1px;font:800 8px ui-monospace,monospace;white-space:nowrap;text-align:center}.point-gun,.point-target{background:transparent;border:0}.point-gun i,.point-target i{display:block;width:18px;height:18px;border:2px solid #fff;border-radius:50%;box-shadow:0 0 0 4px #03080cb0}.point-gun i{background:#2e92ff}.point-target i{background:#ff6e76;border-radius:4px;transform:rotate(45deg)}.lockedbox{border-color:#4b7d59!important}.leaflet-control-zoom a{background:#121c25!important;color:#fff!important;border-color:#33495b!important}.leaflet-control-attribution{font-size:9px!important;background:#03080cbb!important;color:#9aabba!important}@media(max-width:520px){.towerQuick{grid-template-columns:1fr auto}.towerQuick .qt{grid-column:1/3}.towerQuick select{grid-column:1}.towerQuick button{grid-column:2}}';document.head.appendChild(s)}
$('mapSelect')?.addEventListener('change',()=>{gun=target=null;if(map)setTiles($('mapSelect').value);syncMapToPage()});$('zoomIn')?.addEventListener('click',()=>map?.zoomIn());$('zoomOut')?.addEventListener('click',()=>map?.zoomOut());$('reload')?.addEventListener('click',()=>map?.invalidateSize(false));$('clearGun')?.addEventListener('click',()=>{gun=null;syncMapToPage()});$('clearTarget')?.addEventListener('click',()=>{target=null;syncMapToPage()});$('resetMap')?.addEventListener('click',()=>{gun=target=null;syncMapToPage();map?.setView([.5,.5],0,{animate:false})});['sx','sy','tx','ty'].forEach(id=>$(id)?.addEventListener('change',readInputs));window.addEventListener('wardogs:showmap',initMap);window.addEventListener('wardogs:focus',()=>{readInputs()});window.addEventListener('wardogs:resetMap',()=>{gun=target=null;syncMarkers();map?.setView([.5,.5],0,{animate:false})});window.addEventListener('wardogs:i18n',()=>{if(map){refreshLayers();fillQuick()}});
})();