(()=>{
'use strict';
const $=id=>document.getElementById(id);
const DATA='https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator/main/';
const TILES='https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/maps/tiles/';
const TOWER_ICON='https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/assets/map-markers/tower.webp';
const SIZE=16384,UNITS=163.84,MAX_ZOOM=7;
const state={lang:'zh',mode:'gun',gun:null,target:null,gunLocked:false,targetLocked:false,map:null,mapData:null,weapons:null,towerLayer:null,facilityLayer:null,battleLayer:null,gridLayer:null,gunLayer:null,targetLayer:null,routeLayer:null,tileLayer:null,mapPromise:null,tilePending:0};
window.Wardogs11=state;
const I={zh:{sub:'第 1 页 · 坐标输入 / 火控',title:'坐标输入 / 计算',sx:'炮位 X',sy:'炮位 Y',tx:'目标 X',ty:'目标 Y',calc:'开始计算',clear:'清除坐标',bearing:'方位 Code / 方位角',check:'检查',load:'加载火控表',dist:'距离',az:'方位角',dir:'方向',range:'射程状态',mil:'仰角 MIL',arc:'弹道',done:'已计算',inr:'射程内',out:'超出射程',gun:'炮位',target:'目标',setGun:'设置炮位',setTarget:'设置目标',lockGun:'锁定炮位',unlockGun:'解锁炮位',lockTarget:'锁定目标',unlockTarget:'解锁目标',clearGun:'清除炮位',clearTarget:'清除目标',reset:'重置地图',layers:'地图图层',tower:'高塔',facility:'主要建筑 / 设施',battle:'主要战场 / 战区',grid:'1 公里网格',quick:'高塔快速定位',choose:'选择高塔',go:'定位',coordTitle:'坐标快速定位',coordPlaceholder:'例如 84.25, 62.10',coordGo:'定位',ready:'地图就绪',loading:'高清地图加载中',doneMap:'高清层已加载',mapError:'地图加载失败，请重试',help:'单指拖动；双指捏合缩放。点击地图设置点位。输入坐标会同步到地图。放大时标记会自动缩小。',p1:'第 1 页 · 计算',p2:'第 2 页 · 地图',pointSet:'点位已设置',locked:'该点已锁定'},en:{sub:'PAGE 1 · KEY-IN / FIRE CONTROL',title:'KEY-IN / CALCULATOR',sx:'GUN X',sy:'GUN Y',tx:'TARGET X',ty:'TARGET Y',calc:'CALCULATE',clear:'CLEAR COORDS',bearing:'BEARING CODE / AZIMUTH',check:'CHECK',load:'LOAD FIRING TABLE',dist:'DISTANCE',az:'BEARING',dir:'DIRECTION',range:'RANGE',mil:'ELEVATION MIL',arc:'ARC',done:'CALCULATED',inr:'IN RANGE',out:'OUT OF RANGE',gun:'GUN',target:'TARGET',setGun:'SET GUN',setTarget:'SET TARGET',lockGun:'LOCK GUN',unlockGun:'UNLOCK GUN',lockTarget:'LOCK TARGET',unlockTarget:'UNLOCK TARGET',clearGun:'CLEAR GUN',clearTarget:'CLEAR TARGET',reset:'RESET MAP',layers:'MAP LAYERS',tower:'TOWERS',facility:'MAJOR BUILDINGS / FACILITIES',battle:'BATTLE AREAS / ZONES',grid:'1 KM GRID',quick:'TOWER QUICK LOCATION',choose:'SELECT TOWER',go:'GO',coordTitle:'COORDINATE QUICK JUMP',coordPlaceholder:'e.g. 84.25, 62.10',coordGo:'GO',ready:'MAP READY',loading:'LOADING HD MAP',doneMap:'HD LAYER READY',mapError:'MAP LOAD FAILED, RETRY',help:'One finger drags; two fingers pinch to zoom. Tap the map to place a point. Keyed coordinates sync to the map. Markers shrink as you zoom in.',p1:'PAGE 1 · CALC',p2:'PAGE 2 · MAP',pointSet:'POINT SET',locked:'POINT IS LOCKED'}};
const tr=()=>state.lang==='zh'?I.zh:I.en;
function text(id,v){const e=$(id);if(e)e.textContent=v}
function toast(v){const e=$('toast');if(!e)return;e.textContent=v;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1400)}
function i18n(){const t=tr();const m={sub:t.sub,title1:t.title,sxL:t.sx,syL:t.sy,txL:t.tx,tyL:t.ty,calc:t.calc,clear:t.clear,bearingTitle:t.bearing,bearingBtn:t.check,ballisticsBtn:t.load,distL:t.dist,azL:t.az,dirL:t.dir,rangeL:t.range,milL:t.mil,arcL:t.arc,setGun:t.setGun,setTarget:t.setTarget,clearGun:t.clearGun,clearTarget:t.clearTarget,resetMap:t.reset,layersTitle:t.layers,towerText:t.tower,facilityText:t.facility,battleText:t.battle,gridText:t.grid,gunLabel:t.gun,targetLabel:t.target,mapHelp:t.help,nav1:t.p1,nav2:t.p2,lockGun:state.gunLocked?t.unlockGun:t.lockGun,lockTarget:state.targetLocked?t.unlockTarget:t.lockTarget,lang:state.lang==='zh'?'EN':'中文'};Object.entries(m).forEach(([id,v])=>text(id,v));if($('weapon')){$('weapon').options[0].text=state.lang==='zh'?'迫击炮':'Mortar';$('weapon').options[1].text=state.lang==='zh'?'自行火炮 / SPH-2':'SPH-2'};if($('coordQuickTitle'))text('coordQuickTitle',t.coordTitle);if($('coordJump'))$('coordJump').placeholder=t.coordPlaceholder;if($('coordGo'))text('coordGo',t.coordGo);if($('towerQuickTitle'))text('towerQuickTitle',t.quick);if($('towerGo'))text('towerGo',t.go);if($('towerSelect')?.options[0])$('towerSelect').options[0].text=t.choose;if($('mapHud'))$('mapHud').textContent=t.ready}
function direction(b){return['N ↑','NE ↗','E →','SE ↘','S ↓','SW ↙','W ←','NW ↖'][Math.floor((b+22.5)/45)%8]}
function interp(a,m){if(!Array.isArray(a)||!a.length)return null;for(let i=1;i<a.length;i++){if(m<=a[i][0]){const[x1,y1]=a[i-1],[x2,y2]=a[i],f=(m-x1)/(x2-x1);return y1+(y2-y1)*f}}return null}
function ballistics(km){if(!state.weapons)return;const w=state.weapons[$('weapon')?.value];if(!w)return;text('range',km>=w.minRangeKm&&km<=w.maxRangeKm?tr().inr:tr().out);if(w.id==='mortar'){const m=interp(w.ballistics?.single,km);text('mil',m==null?'--':Math.round(m));text('arc',m==null?'--':state.lang==='zh'?'单一':'SINGLE')}else{const lo=interp(w.ballistics?.low,km),hi=interp(w.ballistics?.high,km);text('mil',lo==null?'--':Math.round(lo));text('arc',lo==null?'--':hi==null?'LOW':'LOW '+Math.round(lo)+' / HIGH '+Math.round(hi))}}
async function loadWeapons(){try{const r=await fetch(DATA+'data/weapons.json',{cache:'force-cache'});if(!r.ok)throw 0;const j=await r.json();state.weapons=Object.fromEntries(j.weapons.map(w=>[w.id,w]));const d=parseFloat(($('distance')?.textContent||'').replace(' m',''));if(Number.isFinite(d))ballistics(d/1000)}catch{}}
function gameLL(c){return[1-c.y/UNITS,c.x/UNITS]}
function fromLL(ll){return{x:ll.lng*UNITS,y:(1-ll.lat)*UNITS}}
function locked(kind){return kind==='gun'?state.gunLocked:state.targetLocked}
function syncState(){const g=state.gun,t=state.target;if(g){$('sx').value=g.x.toFixed(2);$('sy').value=g.y.toFixed(2);text('gunCoord',g.x.toFixed(2)+', '+g.y.toFixed(2))}else{$('sx').value='';$('sy').value='';text('gunCoord','--')}if(t){$('tx').value=t.x.toFixed(2);$('ty').value=t.y.toFixed(2);text('targetCoord',t.x.toFixed(2)+', '+t.y.toFixed(2))}else{$('tx').value='';$('ty').value='';text('targetCoord','--')}if($('sx')){$('sx').disabled=state.gunLocked;$('sy').disabled=state.gunLocked}if($('tx')){$('tx').disabled=state.targetLocked;$('ty').disabled=state.targetLocked}$('gunBox')?.classList.toggle('lockedbox',state.gunLocked);$('targetBox')?.classList.toggle('lockedbox',state.targetLocked);syncMapMarkers()}
function calculate(){const sx=parseFloat($('sx').value),sy=parseFloat($('sy').value),tx=parseFloat($('tx').value),ty=parseFloat($('ty').value);if([sx,sy,tx,ty].some(Number.isNaN)){toast(state.lang==='zh'?'请完整输入坐标':'Enter all coordinates');return}if(!state.gunLocked)state.gun={x:sx,y:sy};if(!state.targetLocked)state.target={x:tx,y:ty};if(!state.gun||!state.target)return;const dx=state.target.x-state.gun.x,dy=state.target.y-state.gun.y,m=Math.hypot(dx,dy)*100;let b=Math.atan2(dx,dy)*180/Math.PI;if(b<0)b+=360;text('distance',m.toFixed(1)+' m');text('bearing',b.toFixed(1)+'°');text('direction',direction(b));text('status',tr().done);ballistics(m/1000);syncState();focusPoints()}
function clearResults(){['distance','bearing','direction','range','mil','arc'].forEach(id=>text(id,'--'))}
function syncMapMarkers(){const map=state.map;if(!map)return;state.gunLayer=state.gunLayer||L.layerGroup().addTo(map);state.targetLayer=state.targetLayer||L.layerGroup().addTo(map);state.gunLayer.clearLayers();state.targetLayer.clearLayers();const z=Math.max(.5,Math.min(1,1/Math.sqrt(map.getZoom()+.4)));if(state.gun)state.gunLayer.addLayer(L.marker(gameLL(state.gun),{interactive:false,icon:L.divIcon({className:'v11-point-gun',html:'<i></i>',iconSize:[26*z,26*z],iconAnchor:[13*z,13*z]})}));if(state.target)state.targetLayer.addLayer(L.marker(gameLL(state.target),{interactive:false,icon:L.divIcon({className:'v11-point-target',html:'<i></i>',iconSize:[26*z,26*z],iconAnchor:[13*z,13*z]})}));if(state.routeLayer){state.routeLayer.remove();state.routeLayer=null}if(state.gun&&state.target)state.routeLayer=L.polyline([gameLL(state.gun),gameLL(state.target)],{color:'#ffd65a',weight:1.5,dashArray:'6 5',opacity:.85,interactive:false}).addTo(map)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function label(s){return state.lang==='zh'?String(s).replace(/^Tower /,'高塔 ').replace('Weapons Vendor','武器商人').replace('Garage Vendor','车库商人').replace('Spawn Board','复活板'):s}
function markerScale(base=1){const z=state.map?.getZoom()||0;return Math.max(.38,Math.min(1,base/Math.sqrt(z+.4)))}
function towerMarker(m){const k=markerScale(1),w=32*k,h=46*k;const icon=L.divIcon({className:'v11-tower-marker',html:'<img src="'+TOWER_ICON+'" alt=""><span class="v11-label">'+esc(label(m.label))+'</span>',iconSize:[w,h],iconAnchor:[w/2,h*.53]});return L.marker([1-m.y/SIZE,m.x/SIZE],{icon,keyboard:false})}
function facilityMarker(m){const k=markerScale(.85),w=28*k,h=38*k;const icon=L.divIcon({className:'v11-poi-marker',html:'<span class="v11-facility-dot"></span><span class="v11-label">'+esc(label(m.label))+'</span>',iconSize:[w,h],iconAnchor:[w/2,h*.5]});return L.marker([1-m.y/SIZE,m.x/SIZE],{icon,keyboard:false})}
function refreshMarkerLayers(){if(!state.map||!state.mapData)return;[state.towerLayer,state.facilityLayer,state.battleLayer,state.gridLayer].forEach(l=>l&&l.clearLayers());if($('towerLayer')?.checked!==false)for(const m of state.mapData.markers||[])if(m.icon==='tower'){const mk=towerMarker(m);mk.on('click',e=>{L.DomEvent.stopPropagation(e);setTower(m.label)});state.towerLayer.addLayer(mk)}if($('facilityLayer')?.checked!==false)for(const m of state.mapData.markers||[])if(m.icon!=='tower')state.facilityLayer.addLayer(facilityMarker(m));if($('battleLayer')?.checked!==false)for(const p of state.mapData.polygons||[])state.battleLayer.addLayer(L.polygon((p.points||[]).map(q=>[1-q.y/SIZE,q.x/SIZE]),{color:p.color||'#6fa9ce',weight:2,dashArray:'7 5',fillOpacity:p.fillOpacity==null?.12:p.fillOpacity,interactive:false}));if($('gridLayer')?.checked!==false){for(let i=0;i<=16;i++){const p=i/16;state.gridLayer.addLayer(L.polyline([[p,0],[p,1]],{color:'#65a9df',weight:1,opacity:.14,interactive:false}));state.gridLayer.addLayer(L.polyline([[0,p],[1,p]],{color:'#65a9df',weight:1,opacity:.14,interactive:false}))}}syncMapMarkers()}
function setTower(name){if(!name||!state.mapData)return;const m=(state.mapData.markers||[]).find(x=>x.icon==='tower'&&x.label===name);if(!m)return;const c={x:m.x/100,y:(SIZE-m.y)/100};if(state.mode==='gun'){if(state.gunLocked)return toast(tr().locked);state.gun=c}else{if(state.targetLocked)return toast(tr().locked);state.target=c}syncState();text('mapHud',tr().pointSet);state.map?.setView(gameLL(c),Math.max(3,state.map.getZoom()),{animate:false});calculateIfReady();toast(label(name))}
function calculateIfReady(){if(state.gun&&state.target){const sx=state.gun.x,sy=state.gun.y,tx=state.target.x,ty=state.target.y,m=Math.hypot(tx-sx,ty-sy)*100;let b=Math.atan2(tx-sx,ty-sy)*180/Math.PI;if(b<0)b+=360;text('distance',m.toFixed(1)+' m');text('bearing',b.toFixed(1)+'°');text('direction',direction(b));text('status',tr().done);ballistics(m/1000)}focusPoints()}
function fillQuick(){if(!$('towerQuick')){const d=document.createElement('div');d.id='towerQuick';d.className='v11-quick';d.innerHTML='<div class="qtitle" id="towerQuickTitle"></div><select id="towerSelect"><option value=""></option></select><button id="towerGo"></button>';$('map').parentElement.insertBefore(d,$('map'));$('towerGo').onclick=()=>setTower($('towerSelect').value)}const s=$('towerSelect');if(!s)return;s.innerHTML='<option value="">'+tr().choose+'</option>';for(const m of(state.mapData?.markers||[]).filter(x=>x.icon==='tower').sort((a,b)=>a.label.localeCompare(b.label,undefined,{numeric:true}))){const o=document.createElement('option');o.value=m.label;o.textContent=label(m.label);s.appendChild(o)}}
function fillCoordJump(){if($('coordQuick'))return;const d=document.createElement('div');d.id='coordQuick';d.className='v11-coord';d.innerHTML='<div class="qtitle" id="coordQuickTitle"></div><input id="coordJump" inputmode="decimal" type="text"><button id="coordGo"></button>';$('map').parentElement.insertBefore(d,$('map'));$('coordGo').onclick=()=>jumpToCoord();$('coordJump').addEventListener('keydown',e=>{if(e.key==='Enter')jumpToCoord()})}
function jumpToCoord(){const raw=($('coordJump')?.value||'').trim();const a=raw.replace(/[,;]+/g,' ').split(/\s+/).map(Number).filter(Number.isFinite);if(a.length<2){toast(state.lang==='zh'?'请输入 X,Y 坐标':'Enter X,Y coordinates');return}const c={x:a[0],y:a[1]};if(c.x<0||c.y<0||c.x>100||c.y>100){toast(state.lang==='zh'?'坐标必须在 0–100':'Coordinates must be 0–100');return}if(state.mode==='gun'){if(state.gunLocked)return toast(tr().locked);state.gun=c}else{if(state.targetLocked)return toast(tr().locked);state.target=c}syncState();state.map?.setView(gameLL(c),Math.max(3,state.map.getZoom()),{animate:false});calculateIfReady();toast(tr().pointSet)}
function focusPoints(){if(!state.map)return;if(state.gun&&state.target)state.map.fitBounds(L.latLngBounds(gameLL(state.gun),gameLL(state.target)),{padding:[45,45],maxZoom:5,animate:false});else if(state.gun)state.map.setView(gameLL(state.gun),5,{animate:false});else if(state.target)state.map.setView(gameLL(state.target),5,{animate:false})}
async function loadMapConfig(id){try{const r=await fetch(DATA+'maps/'+id+'.json',{cache:'force-cache'});if(!r.ok)throw 0;state.mapData=await r.json()}catch{state.mapData={id,markers:[],polygons:[]}}}
function setHud(s){text('mapHud',s)}
async function setTiles(id){const map=state.map;if(!map)return;setHud(tr().loading);if(state.tileLayer)map.removeLayer(state.tileLayer);const layer=L.tileLayer(TILES+id+'/zoom_{z}/{x}_{y}.webp',{minZoom:0,maxZoom:MAX_ZOOM,maxNativeZoom:MAX_ZOOM,tileSize:256,noWrap:true,keepBuffer:2,reuseTiles:true,updateWhenIdle:true,updateWhenZooming:false,fadeAnimation:false,detectRetina:false,attribution:'WARDOGS community map'});state.tilePending=0;layer.on('tileloadstart',()=>{state.tilePending++;setHud(tr().loading+' · '+state.tilePending)});layer.on('tileload',()=>{state.tilePending=Math.max(0,state.tilePending-1);if(state.tilePending===0)setHud(tr().doneMap)});layer.on('tileerror',()=>{state.tilePending=Math.max(0,state.tilePending-1);if(state.tilePending===0)setHud(tr().doneMap)});state.tileLayer=layer.addTo(map);await loadMapConfig(id);refreshMarkerLayers();fillQuick();fillCoordJump();syncState();setTimeout(()=>{map.invalidateSize(false);focusPoints()},60)}
async function initMap(){if(state.map){state.map.invalidateSize(false);syncState();focusPoints();return state.map}if(state.mapPromise)return state.mapPromise;state.mapPromise=(async()=>{mapCss();if(!window.L){await new Promise((ok,no)=>{const c=document.createElement('link');c.rel='stylesheet';c.href='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(c);const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}const host=$('map');state.map=L.map(host,{crs:L.CRS.Simple,minZoom:0,maxZoom:MAX_ZOOM,zoomSnap:.5,zoomDelta:.5,zoomControl:true,attributionControl:true,inertia:true,zoomAnimation:true,fadeAnimation:false,markerZoomAnimation:false,tap:false,maxBounds:[[0,0],[1,1]],maxBoundsViscosity:.9});state.map.fitBounds([[0,0],[1,1]],{animate:false});state.towerLayer=L.layerGroup().addTo(state.map);state.facilityLayer=L.layerGroup().addTo(state.map);state.battleLayer=L.layerGroup().addTo(state.map);state.gridLayer=L.layerGroup().addTo(state.map);state.gunLayer=L.layerGroup().addTo(state.map);state.targetLayer=L.layerGroup().addTo(state.map);state.map.on('click',e=>{const c=fromLL(e.latlng);if(state.mode==='gun'){if(state.gunLocked)return toast(tr().locked);state.gun=c}else{if(state.targetLocked)return toast(tr().locked);state.target=c}syncState();calculateIfReady();setHud(tr().pointSet)});state.map.on('zoomend',()=>{refreshMarkerLayers();text('hudZoom','ZOOM '+state.map.getZoom().toFixed(1)+'×')});state.map.on('moveend',()=>syncMapMarkers());await setTiles($('mapSelect')?.value||'bakurani');return state.map})().catch(e=>{setHud(tr().mapError);state.mapPromise=null;throw e});return state.mapPromise}
function mapCss(){if($('v11mapcss'))return;const s=document.createElement('style');s.id='v11mapcss';s.textContent='.v11-quick,.v11-coord{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;background:linear-gradient(#131e28,#091117);border:1px solid #304657;border-radius:12px;padding:9px;margin:8px 0}.v11-coord{grid-template-columns:auto 1fr auto}.v11-quick .qtitle,.v11-coord .qtitle{font:900 10px ui-monospace,monospace;color:#9badbf;white-space:nowrap}.v11-quick select,.v11-coord input{width:100%;min-width:0;background:#070c11;color:#fff;border:1px solid #35495a;border-radius:9px;padding:10px}.v11-quick button,.v11-coord button{background:linear-gradient(#4b9cff,#286fd0);border:1px solid #6ab1ff;color:#fff}.v11-tower-marker,.v11-poi-marker{background:transparent;border:0;transition:transform .08s linear}.v11-tower-marker img{width:100%;height:100%;display:block;object-fit:contain;filter:drop-shadow(0 2px 3px #000)}.v11-poi-marker{display:flex;flex-direction:column;align-items:center;justify-content:flex-start}.v11-facility-dot{display:block;width:40%;aspect-ratio:1;background:#496b82;border:1px solid #c6d9e7;border-radius:3px;box-shadow:0 2px 3px #000}.v11-label{display:block;background:#03070de5;border:1px solid #304552;color:#eef4f9;border-radius:4px;padding:2px 4px;margin-top:1px;font:800 8px ui-monospace,monospace;white-space:nowrap;text-align:center}.v11-point-gun,.v11-point-target{background:transparent;border:0}.v11-point-gun i,.v11-point-target i{display:block;width:18px;height:18px;border:2px solid #fff;border-radius:50%;box-shadow:0 0 0 4px #03080cb0}.v11-point-gun i{background:#2e92ff}.v11-point-target i{background:#ff6e76;border-radius:4px;transform:rotate(45deg)}.leaflet-control-zoom a{background:#121c25!important;color:#fff!important;border-color:#33495b!important}.leaflet-control-attribution{font-size:9px!important;background:#03080cbb!important;color:#9aabba!important}@media(max-width:520px){.v11-quick,.v11-coord{grid-template-columns:1fr auto}.v11-quick .qtitle,.v11-coord .qtitle{grid-column:1/3}.v11-quick select,.v11-coord input{grid-column:1}.v11-quick button,.v11-coord button{grid-column:2}}';document.head.appendChild(s)}
$('lang')?.addEventListener('click',()=>{state.lang=state.lang==='zh'?'en':'zh';i18n();refreshMarkerLayers();fillQuick();fillCoordJump();window.dispatchEvent(new CustomEvent('wardogs:i18n'))});
$('nav1')?.addEventListener('click',()=>{$('page1').classList.add('active');$('page2').classList.remove('active');$('nav1').classList.add('active');$('nav2').classList.remove('active')});
$('nav2')?.addEventListener('click',async()=>{$('page1').classList.remove('active');$('page2').classList.add('active');$('nav1').classList.remove('active');$('nav2').classList.add('active');try{await initMap()}catch{toast(tr().mapError)}});
$('calc')?.addEventListener('click',calculate);
$('clear')?.addEventListener('click',()=>{state.gun=null;state.target=null;state.gunLocked=false;state.targetLocked=false;syncState();clearResults()});
$('bearingBtn')?.addEventListener('click',()=>{const b=+$('bearingInput').value;text('bearingOut',Number.isFinite(b)&&b>=0&&b<360?b.toFixed(1)+'°  '+direction(b):'0–359.9°')});
$('ballisticsBtn')?.addEventListener('click',async()=>{await loadWeapons();const d=parseFloat(($('distance')?.textContent||'').replace(' m',''));if(Number.isFinite(d))ballistics(d/1000)});
$('weapon')?.addEventListener('change',()=>{const d=parseFloat(($('distance')?.textContent||'').replace(' m',''));if(Number.isFinite(d))ballistics(d/1000)});
$('setGun')?.addEventListener('click',()=>{state.mode='gun';$('setGun').classList.add('active');$('setTarget').classList.remove('active')});
$('setTarget')?.addEventListener('click',()=>{state.mode='target';$('setTarget').classList.add('active');$('setGun').classList.remove('active')});
$('lockGun')?.addEventListener('click',()=>{if(!state.gun)return toast(state.lang==='zh'?'先设置炮位':'Set gun first');state.gunLocked=!state.gunLocked;i18n();syncState()});
$('lockTarget')?.addEventListener('click',()=>{if(!state.target)return toast(state.lang==='zh'?'先设置目标':'Set target first');state.targetLocked=!state.targetLocked;i18n();syncState()});
$('clearGun')?.addEventListener('click',()=>{state.gun=null;state.gunLocked=false;syncState();clearResults()});
$('clearTarget')?.addEventListener('click',()=>{state.target=null;state.targetLocked=false;syncState();clearResults()});
$('resetMap')?.addEventListener('click',()=>{state.gun=null;state.target=null;state.gunLocked=false;state.targetLocked=false;syncState();if(state.map)state.map.fitBounds([[0,0],[1,1]],{animate:false});setHud(tr().ready)});
$('zoomIn')?.addEventListener('click',()=>state.map?.zoomIn());$('zoomOut')?.addEventListener('click',()=>state.map?.zoomOut());$('reload')?.addEventListener('click',()=>state.map?.invalidateSize(false));
$('mapSelect')?.addEventListener('change',async()=>{state.gun=null;state.target=null;state.gunLocked=false;state.targetLocked=false;syncState();if(state.map)await setTiles($('mapSelect').value)});
document.querySelectorAll('[data-layer]').forEach(e=>e.addEventListener('change',refreshMarkerLayers));
['sx','sy','tx','ty'].forEach(id=>$(id)?.addEventListener('change',()=>{const s=id[0]==='s';const x=parseFloat($(s?'sx':'tx').value),y=parseFloat($(s?'sy':'ty').value);if(!Number.isFinite(x)||!Number.isFinite(y))return;if(s&&!state.gunLocked)state.gun={x,y};if(!s&&!state.targetLocked)state.target={x,y};syncState();focusPoints()}));
i18n();loadWeapons();
})();