(()=>{
'use strict';
if(window.__WARDOGS_FIELD_V19__)return;window.__WARDOGS_FIELD_V19__=true;
const $=id=>document.getElementById(id);
const DATA='https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator@main/';
const state={lang:'zh',mode:'gun',gun:null,target:null,gunLocked:false,targetLocked:false,weapons:null,map:null,mapData:null};
window.Wardogs19=state;window.Wardogs11=state;
const I={
 zh:{sub:'第 1 页 · 坐标输入 / 火控',title:'坐标输入 / 计算',sx:'炮位 X',sy:'炮位 Y',tx:'目标 X',ty:'目标 Y',calc:'开始计算',clear:'清除坐标',bearing:'方位 Code / 方位角',check:'检查',load:'加载火控表',dist:'距离',az:'方位角',dir:'方向',range:'射程状态',mil:'仰角 MIL',arc:'弹道',done:'已计算',inr:'射程内',out:'超出射程',gun:'炮位',target:'目标',setGun:'设置炮位',setTarget:'设置目标',lockGun:'锁定炮位',unlockGun:'解锁炮位',lockTarget:'锁定目标',unlockTarget:'解锁目标',clearGun:'清除炮位',clearTarget:'清除目标',reset:'重置地图',layers:'地图图层',tower:'活动高塔',inactiveTower:'Inactive Towers',faction:'阵营总部',vendor:'商人 / 补给',spawn:'出生区',grid:'1 公里网格',ready:'地图就绪',doneMap:'高清层已加载',loading:'高清地图加载中',help:'点击地图设置点位；拖动平移；双指或滚轮缩放。高塔快速定位只会设置炮位。坐标定位使用 X / Y 两个输入框。',p1:'第 1 页 · 计算',p2:'第 2 页 · 地图',pointSet:'点位已设置',locked:'该点已锁定',coordTitle:'坐标快速定位',x:'X',y:'Y',go:'定位',choose:'选择高塔',lang:'EN',mapData:'地图资料：社区数据，自动读取最新地图注册表'},
 en:{sub:'PAGE 1 · KEY-IN / FIRE CONTROL',title:'KEY-IN / CALCULATOR',sx:'GUN X',sy:'GUN Y',tx:'TARGET X',ty:'TARGET Y',calc:'CALCULATE',clear:'CLEAR COORDS',bearing:'BEARING CODE / AZIMUTH',check:'CHECK',load:'LOAD FIRING TABLE',dist:'DISTANCE',az:'BEARING',dir:'DIRECTION',range:'RANGE',mil:'ELEVATION MIL',arc:'ARC',done:'CALCULATED',inr:'IN RANGE',out:'OUT OF RANGE',gun:'GUN',target:'TARGET',setGun:'SET GUN',setTarget:'SET TARGET',lockGun:'LOCK GUN',unlockGun:'UNLOCK GUN',lockTarget:'LOCK TARGET',unlockTarget:'UNLOCK TARGET',clearGun:'CLEAR GUN',clearTarget:'CLEAR TARGET',reset:'RESET MAP',layers:'MAP LAYERS',tower:'ACTIVE TOWERS',inactiveTower:'INACTIVE TOWERS',faction:'FACTION HQS',vendor:'VENDORS / SUPPLY',spawn:'SPAWN ZONES',grid:'1 KM GRID',ready:'MAP READY',doneMap:'HD LAYER READY',loading:'LOADING HD MAP',help:'Tap the map to place a point; drag to pan; pinch or wheel to zoom. Tower quick location only sets the gun. Coordinate jump uses separate X / Y inputs.',p1:'PAGE 1 · CALC',p2:'PAGE 2 · MAP',pointSet:'POINT SET',locked:'POINT IS LOCKED',coordTitle:'COORDINATE QUICK JUMP',x:'X',y:'Y',go:'GO',choose:'SELECT TOWER',lang:'中文',mapData:'Map data: community source, auto-loaded from the latest map registry'}};
const tr=()=>state.lang==='zh'?I.zh:I.en;
function text(id,v){const e=$(id);if(e)e.textContent=v}
function toast(v){const e=$('toast');if(!e)return;e.textContent=v;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1400)}
function i18n(){const t=tr();const map={sub:t.sub,title1:t.title,sxL:t.sx,syL:t.sy,txL:t.tx,tyL:t.ty,calc:t.calc,clear:t.clear,bearingTitle:t.bearing,bearingBtn:t.check,ballisticsBtn:t.load,distL:t.dist,azL:t.az,dirL:t.dir,rangeL:t.range,milL:t.mil,arcL:t.arc,setGun:t.setGun,setTarget:t.setTarget,clearGun:t.clearGun,clearTarget:t.clearTarget,resetMap:t.reset,layersTitle:t.layers,towerText:t.tower,inactiveTowerText:t.inactiveTower,factionText:t.faction,vendorText:t.vendor,spawnText:t.spawn,gridText:t.grid,gunLabel:t.gun,targetLabel:t.target,mapHelp:t.help,nav1:t.p1,nav2:t.p2,lang:t.lang};Object.entries(map).forEach(([id,v])=>text(id,v));if($('weapon')){$('weapon').options[0].text=state.lang==='zh'?'迫击炮':'Mortar';$('weapon').options[1].text=state.lang==='zh'?'自行火炮 / SPH-2':'SPH-2'}text('coordTitle',t.coordTitle);text('coordXLabel',t.x);text('coordYLabel',t.y);text('coordGo',t.go);text('towerQuickTitle',t.tower);if($('towerSelect')?.options[0])$('towerSelect').options[0].text=t.choose;text('mapDataNote',t.mapData);if($('mapHud'))$('mapHud').textContent=t.ready;const b=$('brightnessText');if(b)b.textContent=state.lang==='zh'?'地图亮度':'MAP BRIGHTNESS'}
function direction(b){return['N ↑','NE ↗','E →','SE ↘','S ↓','SW ↙','W ←','NW ↖'][Math.floor((b+22.5)/45)%8]}
function interp(a,m){if(!Array.isArray(a)||!a.length)return null;for(let i=1;i<a.length;i++){if(m<=a[i][0]){const[x1,y1]=a[i-1],[x2,y2]=a[i],f=(m-x1)/(x2-x1);return y1+(y2-y1)*f}}return null}
function ballistics(km){if(!state.weapons)return;const w=state.weapons[$('weapon')?.value];if(!w)return;text('range',km>=w.minRangeKm&&km<=w.maxRangeKm?tr().inr:tr().out);if(w.id==='mortar'){const m=interp(w.ballistics?.single,km);text('mil',m==null?'--':Math.round(m));text('arc',m==null?'--':state.lang==='zh'?'单一':'SINGLE')}else{const lo=interp(w.ballistics?.low,km),hi=interp(w.ballistics?.high,km);text('mil',lo==null?'--':Math.round(lo));text('arc',lo==null?'--':hi==null?'LOW':'LOW '+Math.round(lo)+' / HIGH '+Math.round(hi))}}
async function loadWeapons(){try{const r=await fetch(DATA+'data/weapons.json',{cache:'force-cache'});if(!r.ok)throw 0;const j=await r.json();state.weapons=Object.fromEntries(j.weapons.map(w=>[w.id,w]));const d=parseFloat(($('distance')?.textContent||'').replace(' m',''));if(Number.isFinite(d))ballistics(d/1000)}catch{}}
function calculate(){const sx=parseFloat($('sx').value),sy=parseFloat($('sy').value),tx=parseFloat($('tx').value),ty=parseFloat($('ty').value);if([sx,sy,tx,ty].some(Number.isNaN)){toast(state.lang==='zh'?'请完整输入坐标':'Enter all coordinates');return}if(!state.gunLocked)state.gun={x:sx,y:sy};if(!state.targetLocked)state.target={x:tx,y:ty};if(!state.gun||!state.target)return;const dx=state.target.x-state.gun.x,dy=state.target.y-state.gun.y,m=Math.hypot(dx,dy)*100;let b=Math.atan2(dx,dy)*180/Math.PI;if(b<0)b+=360;text('distance',m.toFixed(1)+' m');text('bearing',b.toFixed(1)+'°');text('direction',direction(b));ballistics(m/1000);syncState();state.map?.refresh?.()}
function syncState(){const g=state.gun,t=state.target;if($('sx'))$('sx').value=g?g.x.toFixed(2):'';if($('sy'))$('sy').value=g?g.y.toFixed(2):'';if($('tx'))$('tx').value=t?t.x.toFixed(2):'';if($('ty'))$('ty').value=t?t.y.toFixed(2):'';if($('sx'))$('sx').disabled=state.gunLocked;if($('sy'))$('sy').disabled=state.gunLocked;if($('tx'))$('tx').disabled=state.targetLocked;if($('ty'))$('ty').disabled=state.targetLocked;text('gunCoord',g?`${g.x.toFixed(2)}, ${g.y.toFixed(2)}`:'--');text('targetCoord',t?`${t.x.toFixed(2)}, ${t.y.toFixed(2)}`:'--');$('gunBox')?.classList.toggle('lockedbox',state.gunLocked);$('targetBox')?.classList.toggle('lockedbox',state.targetLocked)}
function clearResults(){['distance','bearing','direction','range','mil','arc'].forEach(id=>text(id,'--'))}
function setMode(mode){state.mode=mode;$('setGun')?.classList.toggle('active',mode==='gun');$('setTarget')?.classList.toggle('active',mode==='target')}
$('lang')?.addEventListener('click',()=>{state.lang=state.lang==='zh'?'en':'zh';i18n();syncState();window.dispatchEvent(new CustomEvent('wardogs:i18n',{detail:{lang:state.lang}}))});
$('setGun')?.addEventListener('click',()=>setMode('gun'));$('setTarget')?.addEventListener('click',()=>setMode('target'));
$('lockGun')?.addEventListener('click',()=>{if(!state.gun)return toast(state.lang==='zh'?'先设置炮位':'Set gun first');state.gunLocked=!state.gunLocked;i18n();syncState()});
$('lockTarget')?.addEventListener('click',()=>{if(!state.target)return toast(state.lang==='zh'?'先设置目标':'Set target first');state.targetLocked=!state.targetLocked;i18n();syncState()});
$('clearGun')?.addEventListener('click',()=>{state.gun=null;state.gunLocked=false;syncState();clearResults();state.map?.refresh?.()});$('clearTarget')?.addEventListener('click',()=>{state.target=null;state.targetLocked=false;syncState();clearResults();state.map?.refresh?.()});
$('clear')?.addEventListener('click',()=>{state.gun=null;state.target=null;state.gunLocked=false;state.targetLocked=false;syncState();clearResults();state.map?.reset?.()});
$('resetMap')?.addEventListener('click',()=>{state.gun=null;state.target=null;state.gunLocked=false;state.targetLocked=false;syncState();clearResults();state.map?.reset?.()});
$('calc')?.addEventListener('click',calculate);$('weapon')?.addEventListener('change',()=>{const d=parseFloat(($('distance')?.textContent||'').replace(' m',''));if(Number.isFinite(d))ballistics(d/1000)});$('bearingBtn')?.addEventListener('click',()=>{const b=+$('bearingInput').value;text('bearingOut',Number.isFinite(b)&&b>=0&&b<360?b.toFixed(1)+'°  '+direction(b):'0–359.9°')});$('ballisticsBtn')?.addEventListener('click',loadWeapons);
['sx','sy','tx','ty'].forEach(id=>$(id)?.addEventListener('change',()=>{const s=id[0]==='s',x=parseFloat($(s?'sx':'tx').value),y=parseFloat($(s?'sy':'ty').value);if(!Number.isFinite(x)||!Number.isFinite(y))return;if(s&&!state.gunLocked)state.gun={x,y};if(!s&&!state.targetLocked)state.target={x,y};syncState();state.map?.focusPoints?.()}));
$('nav1')?.addEventListener('click',()=>{$('page1')?.classList.add('active');$('page2')?.classList.remove('active');$('nav1')?.classList.add('active');$('nav2')?.classList.remove('active')});
$('nav2')?.addEventListener('click',async()=>{$('page1')?.classList.remove('active');$('page2')?.classList.add('active');$('nav1')?.classList.remove('active');$('nav2')?.classList.add('active');try{await state.map?.open?.()}catch{toast(state.lang==='zh'?'地图加载失败':'Map load failed')}});
i18n();syncState();loadWeapons();
})();
