const $=id=>document.getElementById(id);let zh=true,mode='gun',gun=null,target=null,gunLocked=false,targetLocked=false,zoom=1,panX=0,panY=0,ballistics=null,active=new Map(),gesture=null,suppress=false,mapData=null;
const I={zh:{sub:'第1页 • 手动输入 / 火控',title:'手动输入 / 计算',sx:'炮位 X',sy:'炮位 Y',tx:'目标 X',ty:'目标 Y',calc:'⚡ 开始计算',clear:'清除坐标',bearingTitle:'方位 Code / 方位角',check:'检查',load:'↻ 加载火控表',dist:'距离',az:'方位角',dir:'方向',range:'射程状态',mil:'仰角 MIL',arc:'弹道',ready:'准备',done:'已计算',inrange:'射程内',out:'超出射程',p1note:'第1页保留快速手动输入；第2页可直接点地图，炮位和目标独立锁定。',setGun:'📍 设置炮位',setTarget:'🎯 设置目标',lockGun:'🔒 锁定炮位',unlockGun:'🔓 解锁炮位',lockTarget:'🔒 锁定目标',unlockTarget:'🔓 解锁目标',clearGun:'清除炮位',clearTarget:'清除目标',resetMap:'重置地图',layers:'☰ 地图图层',tower:'高塔 / Towers',facility:'主要建筑 / Facilities',battle:'主要战场 / Battle Areas',grid:'1 km 网格',gun:'炮位',target:'目标',mapHelp:'单指拖动地图；双指捏合缩放。选择设置炮位或设置目标后点地图。锁定后对应点不会移动。POI 会随放大自动缩小，保持精确视野。',page1:'⌨️ 第1页 • 计算',page2:'🗺️ 第2页 • 地图'},en:{sub:'PAGE 1 • KEY-IN / FIRE CONTROL',title:'KEY-IN / CALCULATOR',sx:'GUN X',sy:'GUN Y',tx:'TARGET X',ty:'TARGET Y',calc:'⚡ CALCULATE',clear:'CLEAR COORDS',bearingTitle:'BEARING CODE',check:'CHECK',load:'↻ LOAD FIRING TABLE',dist:'DISTANCE',az:'BEARING',dir:'DIRECTION',range:'RANGE',mil:'ELEVATION MIL',arc:'ARC',ready:'READY',done:'CALCULATED',inrange:'IN RANGE',out:'OUT OF RANGE',p1note:'Page 1 keeps the fast manual workflow. Page 2 can place Gun/Target on the map; locks are independent.',setGun:'📍 SET GUN',setTarget:'🎯 SET TARGET',lockGun:'🔒 LOCK GUN',unlockGun:'🔓 UNLOCK GUN',lockTarget:'🔒 LOCK TARGET',unlockTarget:'🔓 UNLOCK TARGET',clearGun:'CLEAR GUN',clearTarget:'CLEAR TARGET',resetMap:'RESET MAP',layers:'☰ MAP LAYERS',tower:'Towers',facility:'Major Buildings / Facilities',battle:'Major Battle Areas',grid:'1 km Grid',gun:'GUN',target:'TARGET',mapHelp:'One finger drags the map; two fingers pinch to zoom. Choose SET GUN or SET TARGET, then tap the map. Locked points stay fixed. POIs shrink as you zoom in so the map stays precise.',page1:'⌨️ PAGE 1 • CALC',page2:'🗺️ PAGE 2 • MAP'}};
const tr=()=>zh?I.zh:I.en;function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1400)}
function applyLang(){let x=tr();$('lang').textContent=zh?'EN':'中文';$('sub').textContent=x.sub;$('title1').textContent=x.title;$('sxL').textContent=x.sx;$('syL').textContent=x.sy;$('txL').textContent=x.tx;$('tyL').textContent=x.ty;$('calc').textContent=x.calc;$('clear').textContent=x.clear;$('bearingTitle').textContent=x.bearingTitle;$('bearingBtn').textContent=x.check;$('ballisticsBtn').textContent=x.load;$('distL').textContent=x.dist;$('azL').textContent=x.az;$('dirL').textContent=x.dir;$('rangeL').textContent=x.range;$('milL').textContent=x.mil;$('arcL').textContent=x.arc;$('p1note').textContent=x.p1note;$('setGun').textContent=x.setGun;$('setTarget').textContent=x.setTarget;$('lockGun').textContent=gunLocked?x.unlockGun:x.lockGun;$('lockTarget').textContent=targetLocked?x.unlockTarget:x.lockTarget;$('clearGun').textContent=x.clearGun;$('clearTarget').textContent=x.clearTarget;$('resetMap').textContent=x.resetMap;$('layersTitle').textContent=x.layers;$('towerText').textContent=x.tower;$('facilityText').textContent=x.facility;$('battleText').textContent=x.battle;$('gridText').textContent=x.grid;$('gunLabel').textContent=x.gun;$('targetLabel').textContent=x.target;$('mapHelp').textContent=x.mapHelp;$('nav1').textContent=x.page1;$('nav2').textContent=x.page2}
function showPage(n){$('page1').classList.toggle('active',n===1);$('page2').classList.toggle('active',n===2);$('nav1').classList.toggle('active',n===1);$('nav2').classList.toggle('active',n===2);if(n===2)loadMap()}
$('nav1').onclick=()=>showPage(1);$('nav2').onclick=()=>showPage(2);$('lang').onclick=()=>{zh=!zh;applyLang();renderMapLayers()};
function dir(b){return ['N ↑','NE ↗','E →','SE ↘','S ↓','SW ↙','W ←','NW ↖'][Math.floor((b+22.5)/45)%8]}
function interp(arr,m){if(!arr||!arr.length)return null;const p=arr.slice().sort((a,b)=>a[0]-b[0]);if(m<p[0][0]||m>p[p.length-1][0])return null;for(let i=1;i<p.length;i++){if(m<=p[i][0]){const [x1,y1]=p[i-1],[x2,y2]=p[i],f=(m-x1)/(x2-x1);return y1+(y2-y1)*f}}return p[p.length-1][1]}
function ball(km){if(!ballistics)return;const w=ballistics[$('weapon').value];if(!w)return;$('range').textContent=km>=w.minRangeKm&&km<=w.maxRangeKm?tr().inrange:tr().out;if(w.id==='mortar'){const m=interp(w.ballistics.single,km);$('mil').textContent=m==null?'--':Math.round(m);$('arc').textContent=m==null?'--':(zh?'单一':'SINGLE')}else{const lo=interp(w.ballistics.low,km),hi=interp(w.ballistics.high,km);$('mil').textContent=lo==null?'--':Math.round(lo);$('arc').textContent=lo==null?'--':hi==null?'LOW':'LOW '+Math.round(lo)+' / HIGH '+Math.round(hi)}}
function calc(){const sx=+$('sx').value,sy=+$('sy').value,tx=+$('tx').value,ty=+$('ty').value;if([sx,sy,tx,ty].some(Number.isNaN)){toast(zh?'请完整输入坐标':'Enter all coordinates');return}const dx=tx-sx,dy=ty-sy,d=Math.hypot(dx,dy)*100;let b=Math.atan2(dx,dy)*180/Math.PI;if(b<0)b+=360;$('distance').textContent=d.toFixed(1)+' m';$('bearing').textContent=b.toFixed(1)+'°';$('direction').textContent=dir(b);ball(d/1000);$('status').textContent=tr().done}
$('calc').onclick=calc;$('clear').onclick=()=>['sx','sy','tx','ty'].forEach(id=>$(id).value='');$('bearingBtn').onclick=()=>{const b=+$('bearingInput').value;$('bearingOut').textContent=Number.isFinite(b)&&b>=0&&b<360?b.toFixed(1)+'°  '+dir(b):'0–359.9°'};$('weapon').onchange=()=>{const d=parseFloat(($('distance').textContent||'').replace(' m',''));if(Number.isFinite(d))ball(d/1000)};
$('ballisticsBtn').onclick=async()=>{try{const j=await fetch('https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator/main/data/weapons.json').then(r=>r.json());ballistics=Object.fromEntries(j.weapons.map(w=>[w.id,w]));const d=parseFloat(($('distance').textContent||'').replace(' m',''));if(Number.isFinite(d))ball(d/1000);toast(tr().load)}catch(e){toast(zh?'火控表暂时不可用':'Firing table unavailable')}};
const BASE={bakurani:'https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/maps/tiles/bakurani/',ozeti:'https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/maps/tiles/ozeti/'};
async function fetchMapData(id){try{return await fetch('https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator/main/maps/'+id+'.json').then(r=>r.json())}catch(e){return null}}
async function loadMap(){mapData=await fetchMapData($('mapSelect').value);renderTiles();renderMapLayers();sync();applyTransform()}
function renderTiles(){const id=$('mapSelect').value,z=Math.min(4,Math.max(1,Math.round(zoom)+1)),n=2**z,w=$('tiles');w.innerHTML='';for(let y=0;y<n;y++)for(let x=0;x<n;x++){const img=new Image();img.className='tile';img.src=BASE[id]+'zoom_'+z+'/'+x+'_'+y+'.webp';img.style.left=x*100/n+'%';img.style.top=y*100/n+'%';img.style.width=100/n+'%';img.style.height=100/n+'%';img.loading='lazy';w.appendChild(img)}}
function pct(x,y){const s=16384;return{x:x/s*100,y:y/s*100}}
function coordFromPct(p){return{x:p.x/100*163.84,y:(1-p.y/100)*163.84}}
function screenPct(cx,cy){const r=$('map').getBoundingClientRect(),u=(cx-r.left-r.width/2-panX)/zoom+r.width/2,v=(cy-r.top-r.height/2-panY)/zoom+r.height/2;return{x:Math.max(0,Math.min(100,u/r.width*100)),y:Math.max(0,Math.min(100,v/r.height*100))}}
function labelOf(s){if(zh){return s.replace('Tower ','高塔 ').replace('Weapons Vendor','武器商人').replace('Garage Vendor','车库商人').replace('Spawn Board','复活板').replace(' Spawn',' 战区').replace('VALKYRA','VALKYRA').replace('MANTICORE','MANTICORE').replace('LONESTAR','LONESTAR')}return s}
function renderMapLayers(){const w=$('world');w.querySelectorAll('.poi,.point').forEach(e=>e.remove());$('zones').innerHTML='';const en={tower:true,facility:false,battle:true,grid:true};document.querySelectorAll('[data-layer]').forEach(c=>en[c.dataset.layer]=c.checked);$('grid').style.display=en.grid?'block':'none';const data=mapData||{markers:[],polygons:[]};for(const m of data.markers||[]){const kind=m.icon==='tower'?'tower':'facility';if(!en[kind])continue;const p=pct(m.x,m.y),e=document.createElement('div');e.className='poi';e.style.left=p.x+'%';e.style.top=p.y+'%';e.style.transform='translate(-50%,-50%) scale('+(1/Math.max(1,zoom)).toFixed(3)+')';const icon=m.icon==='tower'?'🏰':m.icon==='spawn_board'?'📋':m.icon.includes('vendor')?'🔧':'🏭';e.innerHTML='<i>'+icon+'</i><b>'+labelOf(m.label)+'</b>';e.onclick=ev=>{ev.stopPropagation();e.classList.toggle('sel');toast(labelOf(m.label))};w.appendChild(e)}
if(en.battle)for(const poly of data.polygons||[]){const el=document.createElementNS('http://www.w3.org/2000/svg','polygon');el.setAttribute('points',(poly.points||[]).map(p=>p.x+','+p.y).join(' '));el.setAttribute('fill',poly.color||'#5fa8d3');el.setAttribute('fill-opacity','0.12');el.setAttribute('stroke',poly.color||'#5fa8d3');el.setAttribute('stroke-width','18');el.setAttribute('stroke-dasharray','45 28');$('zones').appendChild(el)}if(gun)point(gun,'📍',gunLocked);if(target)point(target,'🎯',targetLocked)}
function point(c,ic,locked){const p=pct(c.x*100,c.y*100),e=document.createElement('div');e.className='point'+(locked?' locked':'');e.style.left=p.x+'%';e.style.top=p.y+'%';e.style.transform='translate(-50%,-50%) scale('+Math.min(1.5,1/Math.max(.75,zoom)).toFixed(3)+')';e.textContent=ic;$('world').appendChild(e)}
function sync(){if(gun){$('gunCoord').textContent=gun.x.toFixed(2)+', '+gun.y.toFixed(2);$('sx').value=gun.x.toFixed(2);$('sy').value=gun.y.toFixed(2)}else $('gunCoord').textContent='--';if(target){$('targetCoord').textContent=target.x.toFixed(2)+', '+target.y.toFixed(2);$('tx').value=target.x.toFixed(2);$('ty').value=target.y.toFixed(2)}else $('targetCoord').textContent='--';$('gunBox').classList.toggle('lockedbox',gunLocked);$('targetBox').classList.toggle('lockedbox',targetLocked)}
function applyTransform(){$('world').style.transform='translate(calc(-50% + '+panX+'px),calc(-50% + '+panY+'px)) scale('+zoom+')';$('hudZoom').textContent='ZOOM '+zoom.toFixed(1)+'×'}
function setMode(m){mode=m;$('setGun').classList.toggle('active',m==='gun');$('setTarget').classList.toggle('active',m==='target')}
$('setGun').onclick=()=>setMode('gun');$('setTarget').onclick=()=>setMode('target');$('lockGun').onclick=()=>{if(!gun)return toast(zh?'先设置炮位':'Set a gun first');gunLocked=!gunLocked;applyLang();renderMapLayers();sync()};$('lockTarget').onclick=()=>{if(!target)return toast(zh?'先设置目标':'Set a target first');targetLocked=!targetLocked;applyLang();renderMapLayers();sync()};$('clearGun').onclick=()=>{gun=null;gunLocked=false;renderMapLayers();sync()};$('clearTarget').onclick=()=>{target=null;targetLocked=false;renderMapLayers();sync()};$('resetMap').onclick=()=>{zoom=1;panX=panY=0;renderTiles();renderMapLayers();applyTransform()};$('reload').onclick=loadMap;$('mapSelect').onchange=()=>{gun=target=null;gunLocked=targetLocked=false;loadMap()};$('zoomIn').onclick=()=>{zoom=Math.min(6,+(zoom+.5).toFixed(2));renderTiles();renderMapLayers();applyTransform()};$('zoomOut').onclick=()=>{zoom=Math.max(1,+(zoom-.5).toFixed(2));renderTiles();renderMapLayers();applyTransform()};document.querySelectorAll('[data-layer]').forEach(c=>c.onchange=renderMapLayers);
$('map').addEventListener('pointerdown',e=>{active.set(e.pointerId,{x:e.clientX,y:e.clientY});if(active.size===1)gesture={type:'pan',x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};else if(active.size===2){const a=[...active.values()];gesture={type:'pinch',dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom,mid:{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2},panX,panY}}e.currentTarget.setPointerCapture?.(e.pointerId)});
$('map').addEventListener('pointermove',e=>{if(!active.has(e.pointerId))return;active.set(e.pointerId,{x:e.clientX,y:e.clientY});if(active.size===2&&gesture?.type==='pinch'){const a=[...active.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),mid={x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2},r=$('map').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,nz=Math.min(6,Math.max(1,gesture.zoom*d/gesture.dist));panX=(mid.x-cx)-((gesture.mid.x-cx-gesture.panX)/gesture.zoom)*nz;panY=(mid.y-cy)-((gesture.mid.y-cy-gesture.panY)/gesture.zoom)*nz;zoom=nz;applyTransform();renderMapLayers();suppress=true;return}if(active.size===1&&gesture?.type==='pan'){const dx=e.clientX-gesture.lastX,dy=e.clientY-gesture.lastY;panX+=dx;panY+=dy;gesture.lastX=e.clientX;gesture.lastY=e.clientY;if(Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>8)gesture.moved=true;if(gesture.moved){applyTransform();renderMapLayers();suppress=true}}});
$('map').addEventListener('pointerup',e=>{active.delete(e.pointerId);if(active.size===0){const g=gesture;gesture=null;if(g&&!g.moved&&!suppress){const c=coordFromPct(screenPct(e.clientX,e.clientY));if(mode==='gun'&&!gunLocked)gun=c;else if(mode==='target'&&!targetLocked)target=c;renderMapLayers();sync();if(gun&&target)calc()}suppress=false}});$('map').addEventListener('pointercancel',e=>{active.delete(e.pointerId);gesture=null;suppress=true});
applyLang();loadMap();