(()=>{
'use strict';
const $=id=>document.getElementById(id);
const defaults={sub:'第 1 页 · 坐标输入 / 火控',title1:'坐标输入 / 计算',sxL:'炮位 X',syL:'炮位 Y',txL:'目标 X',tyL:'目标 Y',calc:'开始计算',clear:'清除坐标',bearingTitle:'方位 Code / 方位角',bearingBtn:'检查',ballisticsBtn:'加载火控表',distL:'距离',azL:'方位角',dirL:'方向',rangeL:'射程状态',milL:'仰角 MIL',arcL:'弹道',setGun:'设置炮位',setTarget:'设置目标',lockGun:'锁定炮位',lockTarget:'锁定目标',clearGun:'清除炮位',clearTarget:'清除目标',resetMap:'重置地图',layersTitle:'地图图层',towerText:'活动高塔',inactiveTowerText:'Inactive Tower',factionText:'阵营总部',vendorText:'商人 / 补给',spawnText:'出生区',gridText:'1 公里网格',gunLabel:'炮位',targetLabel:'目标',mapHelp:'点击地图设置点位；拖动平移；双指或滚轮缩放。缩放会保持手指/光标下的地图位置。高塔快速定位会按照当前选中的“炮位 / 目标”设定。坐标快速定位使用 X / Y 两个输入框。',nav1:'第 1 页 · 计算',nav2:'第 2 页 · 地图',lang:'EN',p1note:'',mapDataNote:'地图资料：自动读取 WARDOGS calculator community map registry'};
const style=document.createElement('style');style.id='wardogs-v31-style';style.textContent='#weapon,#weapon option{background:#060b10!important;color:#fff!important;color-scheme:dark!important}';document.head.appendChild(style);
Object.entries(defaults).forEach(([id,v])=>{const e=$(id);if(e)e.textContent=v});
const core=document.createElement('script');core.src='./app-v19.js?v=31';core.dataset.boot='wardogs-v31-core';
core.onload=()=>{const map=document.createElement('script');map.src='./map-v22.js?v=31';map.dataset.boot='wardogs-v31-map';map.onload=()=>{const fix=document.createElement('script');fix.src='./map-v22-fix.js?v=31';fix.dataset.boot='wardogs-v31-interaction-fix';fix.onload=()=>{const v27=document.createElement('script');v27.src='./map-v27-fix.js?v=31';v27.dataset.boot='wardogs-v31-zoom-tower-fix';v27.onload=()=>{const enh=document.createElement('script');enh.src='./field-enhance-v31.js?v=31';enh.dataset.boot='wardogs-v31-field-enhance';enh.onload=()=>{const ps=document.createElement('script');ps.src='./page-switch-fix.js?v=30';ps.dataset.boot='wardogs-v30-page-switch-fix';document.head.appendChild(ps)};document.head.appendChild(enh)};document.head.appendChild(v27)};document.head.appendChild(fix)};document.head.appendChild(map)};
document.head.appendChild(core);
})();
