(()=>{
'use strict';
if(window.__WARDOGS_MAP_V22__)return;window.__WARDOGS_MAP_V22__=true;
const s=window.Wardogs19||window.Wardogs11;if(!s)return;const $=id=>document.getElementById(id);
const ROOT='https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator/main/maps/';const INDEX=ROOT+'index.json';const ASSET='https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/';const TILE='/tiles/';
const ICON={tower:'assets/map-markers/tower.webp',lonestar:'assets/map-markers/lonestar.webp',manticore:'assets/map-markers/manticore.webp',valkyra:'assets/map-markers/valkyra.webp',weapons_vendor:'assets/map-markers/weapons_vendor.webp',garage_vendor:'assets/map-markers/garage_vendor.webp',spawn_board:'assets/map-markers/spawn_board.webp'};
const Z={zh:{coord:'坐标快速定位',tower:'高塔快速定位',choose:'选择高塔',go:'定位',x:'X',y:'Y',outside:'坐标超出当前地图范围',locked:'炮位已锁定',none:'当前地图资料没有提供非激活高塔坐标',ready:'地图就绪',loading:'高清地图加载中',loaded:'高清层已加载'},en:{coord:'COORDINATE QUICK JUMP',tower:'TOWER QUICK LOCATION',choose:'SELECT TOWER',go:'GO',x:'X',y:'Y',outside:'COORDINATE OUTSIDE CURRENT MAP',locked:'GUN IS LOCKED',none:'No inactive-tower coordinates are provided for this map',ready:'MAP READY',loading:'LOADING HD MAP',loaded:'HD LAYER READY'}};
const tr=()=>Z[s.lang==='zh'?'zh':'en'];
function label(v){let x=String(v??'');return s.lang==='zh'?x.replace(/^Tower\s+/i,'高塔 ').replace(/Weapons Vendor/gi,'武器商人').replace(/Garage Vendor/gi,'车库商人').replace(/Spawn Board/gi,'部署板'):x}
function tower(m){return m?.icon==='tower'||m?.icon==='inactive_tower'}
function inactive(m){return m?.icon==='inactive_tower'||m?.active===false||m?.inactive===true||/inactive|abandoned|非激活|废弃/i.test(String(m?.label||''))}
function point(m){return{x:Number(m.x)/100,y:Number(m.y)/100}}
function sett(){return{tower:$('towerLayer')?.checked!==false,inactive:$('inactiveTowerLayer')?.checked===true,faction:$('factionLayer')?.checked===true,vendor:$('vendorLayer')?.checked===true,spawn:$('spawnLayer')?.checked===true,grid:$('gridLayer')?.checked!==false}}
function cls(){if($('v22css'))return;const st=document.createElement('style');st.id='v22css';st.textContent='.v22-root{position:absolute;inset:0;overflow:hidden;background:#11171c;touch-action:none}.v22-canvas{position:absolute;inset:0;width:100%;height:100%;display:block}.v22-overlay{position:absolute;inset:0;pointer-events:none}.v22-marker{position:absolute;transform:translate(-50%,-50%);display:flex;flex-direction:column;align-items:center;pointer-events:auto}.v22-tower{width:68px;height:72px;cursor:pointer}.v22-tower img{object-fit:contain;filter:drop-shadow(0 2px 3px #000)}.v22-label{margin-top:2px;padding:2px 4px;background:#02060be8;border:1px solid #405361;border-radius:4px;color:#edf4fa;font:900 9px ui-monospace,monospace;white-space:nowrap}.v22-inactive{opacity:.58;filter:grayscale(.8)}.v22-inactive .v22-label{color:#ffb4b4;border-color:#77464b}.v22-poi img{width:24px;height:24px;object-fit:contain;filter:drop-shadow(0 2px 2px #000)}.v22-point{position:absolute;transform:translate(-50%,-50%);width:24px;height:24px;border:2px solid #fff;border-radius:50%;box-shadow:0 0 0 3px #0008;pointer-events:none}.v22-gun{background:#2e92ff}.v22-target{background:#ff6975;border-radius:4px;transform:translate(-50%,-50%) rotate(45deg)}.v22-hud{position:absolute;z-index:9;left:8px;right:8px;top:8px;display:flex;justify-content:space-between;pointer-events:none}.v22-hud span{background:#03080dde;border:1px solid #33495b;border-radius:7px;padding:5px 7px;color:#edf4fa;font:900 9px ui-monospace,monospace}.v22-tools{position:absolute;right:9px;bottom:9px;z-index:10;display:flex;gap:6px}.v22-tools button{width:36px;height:34px;padding:0;border-radius:9px;background:#050b11e8;border:1px solid #465d70;color:#fff;font-weight:900}.v22-quick{display:grid;grid-template-columns:auto 1fr auto;gap:7px;align-items:center;background:linear-gradient(#131e28,#091117);border:1px solid #304657;border-radius:12px;padding:9px;margin:8px 0}.v22-title{font:900 10px ui-monospace,monospace;color:#9badbf;white-space:nowrap}.v22-coordgrid{grid-column:1/3;display:grid;grid-template-columns:1fr 1fr;gap:7px}.v22-field label{display:block;color:#8fa1b3;font:9px ui-monospace,monospace;margin-bottom:4px}.v22-field input,.v22-quick select{width:100%;background:#070c11;color:#fff;border:1px solid #35495a;border-radius:9px;padding:10px}.v22-quick button{background:linear-gradient(#4b9cff,#286fd0);border:1px solid #6ab1ff;color:#fff;border-radius:9px;padding:10px 13px;font-weight:900}.v22-readout{grid-column:1/-1;background:#080f15;border:1px solid #283a49;border-radius:8px;padding:7px;text-align:center;color:#ffd45b;font:900 9px ui-monospace,monospace}.v22-note{grid-column:1/-1;color:#8fa1b3;font:8px ui-monospace,monospace;text-align:center}@media(max-width:520px){.v22-quick{grid-template-columns:1fr auto}.v22-title{grid-column:1/-1}.v22-coordgrid{grid-column:1}.v22-quick .v22-coord-go{grid-column:2;grid-row:2}}';document.head.appendChild(st)}
function toast(v){const e=$('toast');if(!e)return;e.textContent=v;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1300)}
function clean(){for(const id of ['towerQuick','coordQuick'])$(id)?.remove();document.querySelectorAll('.v11-quick,.v11-coord,.v14-quick,.v18-quick,.v19-quick,.v20-quick,.v21-quick,.v22-quick').forEach(e=>e.remove())}
function sync(){const put=(id,v)=>{const e=$(id);if(e)e.value=v==null?'':Number(v).toFixed(2)};put('sx',s.gun?.x);put('sy',s.gun?.y);put('tx',s.target?.x);put('ty',s.target?.y);if($('sx'))$('sx').disabled=!!s.gunLocked;if($('sy'))$('sy').disabled=!!s.gunLocked;if($('tx'))$('tx').disabled=!!s.targetLocked;if($('ty'))$('ty').disabled=!!s.targetLocked;if($('gunCoord'))$('gunCoord').textContent=s.gun?`${s.gun.x.toFixed(2)}, ${s.gun.y.toFixed(2)}`:'--';if($('targetCoord'))$('targetCoord').textContent=s.target?`${s.target.x.toFixed(2)}, ${s.target.y.toFixed(2)}`:'--'}
function create(id,data){cls();const host=$('map');host.replaceChildren();const root=document.createElement('div');root.className='v22-root';const canvas=document.createElement('canvas');canvas.className='v22-canvas';const overlay=document.createElement('div');overlay.className='v22-overlay';const hudEl=document.createElement('div');hudEl.className='v22-hud';hudEl.innerHTML='<span id="mapHud"></span><span id="hudZoom"></span>';const tools=document.createElement('div');tools.className='v22-tools';tools.innerHTML='<button data-fit>⌂</button><button data-full>⛶</button>';root.append(canvas,overlay,hudEl,tools);host.appendChild(root);const ctx=canvas.getContext('2d',{alpha:false});const q={id,data,zoom:0,px:0,py:0,cache:new Map(),loaded:0,ptr:new Map(),drag:null,pinch:null,last:null,raf:0,dead:false,view:{...data.bounds},tile:{...data.tileBounds},tiles:{...data.tiles}};
function view(){const W=host.clientWidth,H=host.clientHeight,bw=q.view.maxX-q.view.minX,bh=q.view.maxY-q.view.minY,base=Math.min(Math.max(1,(W-16)/bw),Math.max(1,(H-16)/bh)),scale=base*2**q.zoom,mw=bw*scale,mh=bh*scale;return{W,H,scale,mw,mh,left:(W-mw)/2+q.px,top:(H-mh)/2+q.py,bounds:q.view}}
function w2s(x,y){const v=view();return{x:v.left+(x-v.bounds.minX)*v.scale,y:v.top+(v.bounds.maxY-y)*v.scale}}
function s2w(x,y){const v=view();return{x:v.bounds.minX+(x-v.left)/v.scale,y:v.bounds.maxY-(y-v.top)/v.scale}}
function clamp(){const v=view(),mx=Math.max(0,(v.mw-v.W)/2),my=Math.max(0,(v.mh-v.H)/2);q.px=Math.max(-mx,Math.min(mx,q.px));q.py=Math.max(-my,Math.min(my,q.py))}
function tz(){const v=view(),world=q.tile.maxX-q.tile.minX,base=q.tiles.tileSize/world;return Math.max(0,Math.min(Number(q.tiles.maxZoom??7),Math.round(Math.log2(v.scale/base))))}
function loadTile(z,x,y){if(x<0||y<0||x>=2**z||y>=2**z)return null;const k=`${id}:${z}:${x}:${y}`;if(q.cache.has(k))return q.cache.get(k);const c={img:new Image(),ok:false};q.cache.set(k,c);c.img.decoding='async';c.img.onload=()=>{c.ok=true;q.loaded++;draw()};c.img.onerror=()=>draw();c.img.src=`${TILE}${id}/zoom_${z}/${x}_${y}.webp`;return c}
function ancestor(z,x,y){for(let a=z-1;a>=0;a--){const d=z-a,n=2**d,px=Math.floor(x/n),py=Math.floor(y/n),c=q.cache.get(`${id}:${a}:${px}:${py}`);if(c?.ok)return{c,sx:(x%n)*(256/n),sy:(y%n)*(256/n),ss:256/n}}return null}
function tiles(){const v=view(),z=tz(),n=2**z,tw=(q.tile.maxX-q.tile.minX)/n,th=(q.tile.maxY-q.tile.minY)/n,a=s2w(0,0),b=s2w(v.W,v.H),left=Math.max(q.tile.minX,Math.min(a.x,b.x)-tw),right=Math.min(q.tile.maxX,Math.max(a.x,b.x)+tw),bottom=Math.max(q.tile.minY,Math.min(a.y,b.y)-th),top=Math.min(q.tile.maxY,Math.max(a.y,b.y)+th),x0=Math.max(0,Math.floor((left-q.tile.minX)/tw)-1),x1=Math.min(n-1,Math.floor((right-q.tile.minX)/tw)+1),y0=Math.max(0,Math.floor((q.tile.maxY-top)/th)-1),y1=Math.min(n-1,Math.floor((q.tile.maxY-bottom)/th)+1);ctx.save();ctx.beginPath();ctx.rect(v.left,v.top,v.mw,v.mh);ctx.clip();for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const wx=q.tile.minX+x*tw,wy=q.tile.maxY-y*th,p=w2s(wx,wy),sw=tw*v.scale+1,sh=th*v.scale+1,c=loadTile(z,x,y);if(c?.ok)ctx.drawImage(c.img,p.x,p.y,sw,sh);else{const an=ancestor(z,x,y);if(an)ctx.drawImage(an.c.img,an.sx,an.sy,an.ss,an.ss,p.x,p.y,sw,sh)}}ctx.restore()}
function grid(){if(!sett().grid)return;const v=view();for(let x=Math.ceil(v.bounds.minX);x<=Math.floor(v.bounds.maxX);x++){const p=w2s(x,v.bounds.maxY);ctx.strokeStyle='rgba(90,160,210,.22)';ctx.lineWidth=x%10===0?1.1:.6;ctx.beginPath();ctx.moveTo(p.x,v.top);ctx.lineTo(p.x,v.top+v.mh);ctx.stroke()}for(let y=Math.ceil(v.bounds.minY);y<=Math.floor(v.bounds.maxY);y++){const p=w2s(v.bounds.minX,y);ctx.strokeStyle='rgba(90,160,210,.22)';ctx.lineWidth=y%10===0?1.1:.6;ctx.beginPath();ctx.moveTo(v.left,p.y);ctx.lineTo(v.left+v.mw,p.y);ctx.stroke()}}
function zones(){if(!sett().spawn)return;for(const p of q.data.polygons||[]){const pts=(p.points||[]).map(v=>w2s(Number(v.x)/100,Number(v.y)/100));if(pts.length<3)continue;ctx.save();ctx.beginPath();pts.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.closePath();ctx.fillStyle=p.color||'#6fa9ce';ctx.globalAlpha=p.fillOpacity??.12;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=p.color||'#6fa9ce';ctx.lineWidth=p.strokeWidth||2;ctx.setLineDash(p.dashed?[8,6]:[]);ctx.stroke();ctx.restore()}}
function markers(){overlay.replaceChildren();const st=sett(),k=Math.max(.72,1.06/2**(q.zoom*.17));for(const m of q.data.markers||[]){if(!visible(m,st))continue;const c=point(m),p=w2s(c.x,c.y);if(p.x<-110||p.x>host.clientWidth+110||p.y<-110||p.y>host.clientHeight+110)continue;const tow=tower(m),el=document.createElement('div');el.className=`v22-marker ${tow?'v22-tower':'v22-poi'}`+(inactive(m)?' v22-inactive':'');el.style.left=p.x+'px';el.style.top=p.y+'px';el.dataset.label=String(m.label||'');el.dataset.icon=String(m.icon||'');el.dataset.x=c.x.toFixed(2);el.dataset.y=c.y.toFixed(2);el.title=`${label(m.label)} · X ${c.x.toFixed(2)} / Y ${c.y.toFixed(2)}`;if(tow){const img=document.createElement('img');const size=Math.round(34*k);img.width=size;img.height=size;img.src=ASSET+ICON.tower;img.alt='';el.append(img)}else if(ICON[m.icon]){const img=document.createElement('img');img.src=ASSET+ICON[m.icon];img.alt='';el.append(img)}else{const d=document.createElement('span');d.className='v22-dot';el.append(d)}const sp=document.createElement('span');sp.className='v22-label';sp.textContent=label(m.label);el.append(sp);if(tow)el.addEventListener('click',e=>{e.stopPropagation();setGun(c,m.label)});overlay.append(el)}if(s.gun){const p=w2s(s.gun.x,s.gun.y),e=document.createElement('div');e.className='v22-point v22-gun';e.style.left=p.x+'px';e.style.top=p.y+'px';overlay.append(e)}if(s.target){const p=w2s(s.target.x,s.target.y),e=document.createElement('div');e.className='v22-point v22-target';e.style.left=p.x+'px';e.style.top=p.y+'px';overlay.append(e)}}
function visible(m,st){if(tower(m))return inactive(m)?st.inactive:st.tower;if(['lonestar','manticore','valkyra'].includes(m.icon))return st.faction;if(['weapons_vendor','garage_vendor','spawn_board'].includes(m.icon))return st.vendor;return false}
function setGun(c,l){if(s.gunLocked){toast(tr().locked);return}s.gun={...c};s.mapData=q.data;sync();focus(c);toast(label(l))}
function setPoint(c){if(s.mode==='gun'){if(s.gunLocked)return toast(tr().locked);s.gun=c}else{if(s.targetLocked)return toast(stateTargetLock());s.target=c}sync();draw()}
function stateTargetLock(){return s.lang==='zh'?'目标已锁定':'TARGET IS LOCKED'}
function focus(c){q.zoom=Math.max(2,q.zoom);const v=view();q.px+=v.W/2-(v.left+(c.x-v.bounds.minX)*v.scale);q.py+=v.H/2-(v.top+(v.bounds.maxY-c.y)*v.scale);clamp();draw()}
function quick(){clean();const b=document.createElement('div');b.id='v22-quick';b.className='v22-quick';b.innerHTML='<div id="coordTitle" class="v22-title"></div><div class="v22-coordgrid"><div class="v22-field"><label id="coordXLabel"></label><input id="v22-x" inputmode="decimal"></div><div class="v22-field"><label id="coordYLabel"></label><input id="v22-y" inputmode="decimal"></div></div><button id="coordGo" class="v22-coord-go"></button><div id="towerQuickTitle" class="v22-title"></div><div><select id="towerSelect"><option></option></select></div><button id="towerGo"></button><div id="mapHoverCoord" class="v22-readout">X -- / Y --</div><div id="inactiveHint" class="v22-note"></div>';host.parentElement.insertBefore(b,host);const sel=$('towerSelect');for(const m of (q.data.markers||[]).filter(m=>m.icon==='tower'&&!inactive(m))){const o=document.createElement('option');o.value=m.label;o.textContent=label(m.label);sel.append(o)}$('coordGo').onclick=()=>{const x=Number($('v22-x').value),y=Number($('v22-y').value);if(Number.isFinite(x)&&Number.isFinite(y)&&x>=q.view.minX&&x<=q.view.maxX&&y>=q.view.minY&&y<=q.view.maxY){setPoint({x,y});focus({x,y})}else toast(tr().outside)};$('towerGo').onclick=()=>{const m=(q.data.markers||[]).find(m=>m.icon==='tower'&&!inactive(m)&&m.label===sel.value);if(m)setGun(point(m),m.label)};labels()}
function labels(){const a=tr();if($('coordTitle'))$('coordTitle').textContent=a.coord;if($('towerQuickTitle'))$('towerQuickTitle').textContent=a.tower;if($('coordXLabel'))$('coordXLabel').textContent=a.x;if($('coordYLabel'))$('coordYLabel').textContent=a.y;if($('coordGo'))$('coordGo').textContent=a.go;if($('towerGo'))$('towerGo').textContent=a.go;if($('towerSelect')?.options[0])$('towerSelect').options[0].text=a.choose;const n=(q.data.markers||[]).filter(inactive).length;if($('inactiveHint'))$('inactiveHint').textContent=n?`${a.inactive}: ${n}`:a.none;if($('mapHud'))$('mapHud').textContent=q.loaded?a.loaded:a.loading}
function draw(){if(q.dead)return;cancelAnimationFrame(q.raf);q.raf=requestAnimationFrame(()=>{const v=view(),b=$('mapBrightness');ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#10171d';ctx.fillRect(0,0,v.W,v.H);if(b)canvas.style.filter=`brightness(${b.value}%)`;tiles();zones();grid();markers();if($('hudZoom'))$('hudZoom').textContent=`ZOOM ${Math.round(2**q.zoom)}×`;if($('mapHoverCoord')&&q.last)$('mapHoverCoord').textContent=`X ${q.last.x.toFixed(2)} / Y ${q.last.y.toFixed(2)}`})}
function resize(){const d=Math.max(1,Math.min(2,devicePixelRatio||1)),w=host.clientWidth,h=host.clientHeight;canvas.width=Math.max(1,Math.round(w*d));canvas.height=Math.max(1,Math.round(h*d));canvas.style.width=w+'px';canvas.style.height=h+'px';draw()}
function setCoord(e){const r=root.getBoundingClientRect(),c=s2w(e.clientX-r.left,e.clientY-r.top);if(c.x>=q.view.minX&&c.x<=q.view.maxX&&c.y>=q.view.minY&&c.y<=q.view.maxY){q.last=c;if($('mapHoverCoord'))$('mapHoverCoord').textContent=`X ${c.x.toFixed(2)} / Y ${c.y.toFixed(2)}`}}
function bind(){tools.querySelector('[data-fit]')?.addEventListener('click',()=>{q.zoom=0;q.px=q.py=0;draw()});tools.querySelector('[data-full]')?.addEventListener('click',async()=>{try{if(!document.fullscreenElement)await host.requestFullscreen();else await document.exitFullscreen()}catch{host.classList.toggle('v20-fullscreen')}});for(const id of ['zoomIn','zoomOut'])$(id)?.addEventListener('click',()=>{q.zoom=Math.max(0,Math.min(MAX_ZOOM,q.zoom+(id==='zoomIn'?1:-1)));clamp();draw()});$('reload')?.addEventListener('click',()=>{q.cache.clear();q.loaded=0;draw()});for(const id of ['towerLayer','inactiveTowerLayer','factionLayer','vendorLayer','spawnLayer','gridLayer','mapBrightness'])$(id)?.addEventListener('change',draw);root.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;const r=root.getBoundingClientRect();q.ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});if(q.ptr.size===2){const a=[...q.ptr.values()];q.pinch={d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),z:q.zoom};q.drag=null;return}root.setPointerCapture?.(e.pointerId);q.drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:q.px,py:q.py};setCoord(e)});root.addEventListener('pointermove',e=>{q.ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});setCoord(e);if(q.pinch&&q.ptr.size===2){const a=[...q.ptr.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);q.zoom=Math.max(0,Math.min(MAX_ZOOM,q.pinch.z+Math.log2(d/Math.max(1,q.pinch.d))));clamp();draw();return}if(q.drag?.id===e.pointerId){q.px=q.drag.px+e.clientX-q.drag.x;q.py=q.drag.py+e.clientY-q.drag.y;clamp();draw()}});root.addEventListener('pointerup',e=>{q.ptr.delete(e.pointerId);if(q.ptr.size<2)q.pinch=null;const d=q.drag;q.drag=null;if(d&&d.id===e.pointerId&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<6){const r=root.getBoundingClientRect();setPoint(s2w(e.clientX-r.left,e.clientY-r.top))}});root.addEventListener('pointercancel',e=>{q.ptr.delete(e.pointerId);q.drag=null;q.pinch=null});root.addEventListener('wheel',e=>{e.preventDefault();const r=root.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,c=s2w(mx,my);q.zoom=Math.max(0,Math.min(MAX_ZOOM,q.zoom+(e.deltaY<0?1:-1)));const np=w2s(c.x,c.y);q.px+=mx-np.x;q.py+=my-np.y;clamp();draw()},{passive:false})}
function api(){return{id,q,resize,open:resize,refresh:()=>{sync();labels();draw()},reset:()=>{q.zoom=0;q.px=q.py=0;draw()},focusPoints:()=>s.gun?focus(s.gun):s.target&&focus(s.target),getZoom:()=>q.zoom,setData:d=>{q.data=d;q.view={...d.bounds};q.tile={...d.tileBounds};q.tiles={...d.tiles};q.zoom=0;q.px=q.py=0;quick();sync();resize()},destroy:()=>{q.dead=true;cancelAnimationFrame(q.raf);clean()}}}
bind();resize();return api()}
let current=null;
async function build(){const id=$('mapSelect')?.value||'bakurani';current?.destroy?.();try{const r=await fetch(ROOT+id+'.json',{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();current=create(id,data);s.map=current;s.mapData=data;current.setData(data)}catch{toast(s.lang==='zh'?'地图资料加载失败':'MAP DATA FAILED')}}
$('nav1')?.addEventListener('click',()=>{$('page1')?.classList.add('active');$('page2')?.classList.remove('active')});$('nav2')?.addEventListener('click',async()=>{$('page1')?.classList.remove('active');$('page2')?.classList.add('active');if(current)current.open();else await build()});$('mapSelect')?.addEventListener('change',()=>{s.gun=null;s.target=null;s.gunLocked=false;s.targetLocked=false;build()});window.addEventListener('resize',()=>current?.resize());window.addEventListener('orientationchange',()=>setTimeout(()=>current?.resize(),50));window.addEventListener('wardogs:i18n',()=>current?.refresh());
fillRegistry().finally(()=>{if($('page2')?.classList.contains('active'))build()});
async function fillRegistry(){try{const r=await fetch(INDEX,{cache:'no-store'}),a=await r.json(),sel=$('mapSelect');if(!sel||!Array.isArray(a))return;const cur=sel.value||'bakurani';sel.innerHTML='';for(const x of a){const id=String(x).replace(/\.json$/,'');const o=document.createElement('option');o.value=id;o.textContent=id.toUpperCase();sel.append(o)}if([...sel.options].some(o=>o.value===cur))sel.value=cur}catch{}}
})();
