(()=>{
'use strict';
const DATA='https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator/main/maps/';
const TILE_ROOT='/tiles/';
const ASSET='https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/';
const TILE_CACHE=new Map(),MAX_ZOOM=7;
const ICON={tower:'assets/map-markers/tower.webp',lonestar:'assets/map-markers/lonestar.webp',manticore:'assets/map-markers/manticore.webp',valkyra:'assets/map-markers/valkyra.webp',weapons_vendor:'assets/map-markers/weapons_vendor.webp',garage_vendor:'assets/map-markers/garage_vendor.webp',spawn_board:'assets/map-markers/spawn_board.webp'};
function boot(){const s=window.Wardogs11,h=document.getElementById('map');if(!s||!h){setTimeout(boot,80);return}if(s.__mapV18)return;s.__mapV18=true;cleanup();document.getElementById('nav2')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();show(2);build()},true);document.getElementById('nav1')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();show(1)},true);document.getElementById('mapSelect')?.addEventListener('change',()=>build(true));window.addEventListener('resize',()=>setTimeout(()=>s.canvasMap?.resize(),50),{passive:true});window.addEventListener('orientationchange',()=>setTimeout(()=>s.canvasMap?.resize(),50),{passive:true});setTimeout(()=>{if(document.getElementById('page2')?.classList.contains('active'))build()},80)}
function cleanup(){for(const id of ['towerQuick','coordQuick'])document.getElementById(id)?.remove();document.querySelectorAll('.v11-quick,.v11-coord,.v14-quick,.v18-quick').forEach(e=>e.remove())}
function show(n){cleanup();document.getElementById('page1')?.classList.toggle('active',n===1);document.getElementById('page2')?.classList.toggle('active',n===2);document.getElementById('nav1')?.classList.toggle('active',n===1);document.getElementById('nav2')?.classList.toggle('active',n===2)}
async function load(id){const r=await fetch(DATA+id+'.json',{cache:'no-store'});if(!r.ok)throw Error('map config '+r.status);return r.json()}
function build(force=false){const s=window.Wardogs11,h=document.getElementById('map');if(!s||!h||!document.getElementById('page2')?.classList.contains('active')||!h.clientWidth||!h.clientHeight)return;cleanup();const id=document.getElementById('mapSelect')?.value||'bakurani';if(s.canvasMap?.id===id&&!force){s.canvasMap.resize();return}s.canvasMap?.destroy?.();h.replaceChildren();const hud=document.createElement('div');hud.className='v18-hud';hud.innerHTML='<span id="mapHud">加载 WARDOGS 高清地形…</span><span id="hudZoom">ZOOM 1×</span>';h.appendChild(hud);const m=createMap(h,id);s.canvasMap=m;load(id).then(d=>{if(s.canvasMap===m)m.setData(d)}).catch(e=>{console.error(e);m.setHud('地图资料加载失败')})}
function createMap(host,id){const root=document.createElement('div');root.className='v18-map-root';const canvas=document.createElement('canvas');canvas.className='v18-map-canvas';const overlay=document.createElement('div');overlay.className='v18-marker-layer';const tools=document.createElement('div');tools.className='v18-map-tools';tools.innerHTML='<button data-fit>⌂</button><button data-full>⛶</button>';root.append(canvas,overlay,tools);host.appendChild(root);const ctx=canvas.getContext('2d',{alpha:false}),st=window.Wardogs11;const q={id,data:null,zoom:0,panX:0,panY:0,view:{minX:0,maxX:163.84,minY:0,maxY:163.84},tile:{minX:0,maxX:163.84,minY:0,maxY:163.84},tiles:{tileSize:256,minZoom:0,maxZoom:7,extension:'webp'},markers:[],polygons:[],dpr:Math.max(1,Math.min(2,devicePixelRatio||1)),raf:0,destroyed:false,loadOk:0,ptr:new Map(),pinch:null,drag:null,last:null};
function resize(){q.dpr=Math.max(1,Math.min(2,devicePixelRatio||1));const w=host.clientWidth,h=host.clientHeight;canvas.width=Math.max(1,Math.round(w*q.dpr));canvas.height=Math.max(1,Math.round(h*q.dpr));canvas.style.width=w+'px';canvas.style.height=h+'px';draw()}
function view(){const W=host.clientWidth,H=host.clientHeight,bw=q.view.maxX-q.view.minX,bh=q.view.maxY-q.view.minY,pad=12,base=Math.min(Math.max(1,(W-pad*2)/bw),Math.max(1,(H-pad*2)/bh)),scale=base*2**q.zoom,mw=bw*scale,mh=bh*scale;return{scale,mw,mh,left:(W-mw)/2+q.panX,top:(H-mh)/2+q.panY,bounds:q.view}}
function w2s(x,y){const v=view();return{x:v.left+(x-v.bounds.minX)*v.scale,y:v.top+(v.bounds.maxY-y)*v.scale}}
function s2w(x,y){const v=view();return{x:v.bounds.minX+(x-v.left)/v.scale,y:v.bounds.maxY-(y-v.top)/v.scale}}
function clampPan(){const v=view(),W=host.clientWidth,H=host.clientHeight;const px=v.mw<=W?0:Math.max(W-v.mw,Math.min(0,q.panX));const py=v.mh<=H?0:Math.max(H-v.mh,Math.min(0,q.panY));q.panX=px;q.panY=py}
function tileZoom(){const v=view(),world=q.tile.maxX-q.tile.minX,base=q.tiles.tileSize/world,raw=Math.log2(v.scale/base);return Math.max(q.tiles.minZoom,Math.min(q.tiles.maxZoom,Math.round(raw)))}
function key(z,x,y){return `${id}:${z}:${x}:${y}`}
function loadTile(z,x,y){if(x<0||y<0||x>=2**z||y>=2**z)return null;const k=key(z,x,y);let t=TILE_CACHE.get(k);if(t)return t;t={img:new Image(),loaded:false,failed:false};TILE_CACHE.set(k,t);t.img.decoding='async';t.img.onload=()=>{t.loaded=true;q.loadOk++;window.__wardogsTerrainOk=true;draw()};t.img.onerror=()=>{t.failed=true;draw()};t.img.src=`${TILE_ROOT}${id}/zoom_${z}/${x}_${y}.${q.tiles.extension}`;return t}
function anc(z,x,y){for(let a=z-1;a>=q.tiles.minZoom;a--){const d=z-a,s=2**d,px=Math.floor(x/s),py=Math.floor(y/s),t=TILE_CACHE.get(key(a,px,py));if(t?.loaded&&!t.failed)return{t,sx:(x%s)*(256/s),sy:(y%s)*(256/s),ss:256/s}}return null}
function drawTiles(){const v=view(),z=tileZoom(),n=2**z,tw=(q.tile.maxX-q.tile.minX)/n,th=(q.tile.maxY-q.tile.minY)/n,tl=s2w(0,0),br=s2w(host.clientWidth,host.clientHeight),left=Math.max(q.view.minX,q.tile.minX,Math.min(tl.x,br.x)-tw),right=Math.min(q.view.maxX,q.tile.maxX,Math.max(tl.x,br.x)+tw),bottom=Math.max(q.view.minY,q.tile.minY,Math.min(tl.y,br.y)-th),top=Math.min(q.view.maxY,q.tile.maxY,Math.max(tl.y,br.y)+th);if(left>=right||bottom>=top)return;const minX=Math.max(0,Math.floor((left-q.tile.minX)/tw)-1),maxX=Math.min(n-1,Math.floor((right-q.tile.minX)/tw)+1),minY=Math.max(0,Math.floor((q.tile.maxY-top)/th)-1),maxY=Math.min(n-1,Math.floor((q.tile.maxY-bottom)/th)+1);ctx.save();ctx.beginPath();ctx.rect(v.left,v.top,v.mw,v.mh);ctx.clip();for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const wx=q.tile.minX+x*tw,wy=q.tile.maxY-y*th,p=w2s(wx,wy),sw=tw*v.scale+1,sh=th*v.scale+1,t=loadTile(z,x,y);if(t?.loaded&&!t.failed)ctx.drawImage(t.img,p.x,p.y,sw,sh);else{const a=anc(z,x,y);if(a)ctx.drawImage(a.t.img,a.sx,a.sy,a.ss,a.ss,p.x,p.y,sw,sh)}}ctx.restore()}
function drawGrid(){if(document.getElementById('gridLayer')?.checked===false)return;const v=view(),startX=Math.ceil(v.bounds.minX),endX=Math.floor(v.bounds.maxX),startY=Math.ceil(v.bounds.minY),endY=Math.floor(v.bounds.maxY);for(let x=startX;x<=endX;x++){const p=w2s(x,v.bounds.maxY),major=x%10===0;ctx.strokeStyle=major?'rgba(150,160,168,.6)':'rgba(100,112,120,.3)';ctx.lineWidth=major?1:.65;ctx.beginPath();ctx.moveTo(p.x,v.top);ctx.lineTo(p.x,v.top+v.mh);ctx.stroke()}for(let y=startY;y<=endY;y++){const p=w2s(v.bounds.minX,y),major=y%10===0;ctx.strokeStyle=major?'rgba(150,160,168,.6)':'rgba(100,112,120,.3)';ctx.lineWidth=major?1:.65;ctx.beginPath();ctx.moveTo(v.left,p.y);ctx.lineTo(v.left+v.mw,p.y);ctx.stroke()}}
function drawPolys(){if(document.getElementById('spawnLayer')?.checked===false)return;for(const poly of q.polygons){const pts=(poly.points||[]).map(p=>w2s(Number(p.x)/100,Number(p.y)/100));if(pts.length<3)continue;ctx.save();ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=poly.color||'#6fa9ce';ctx.globalAlpha=poly.fillOpacity??.12;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=poly.color||'#6fa9ce';ctx.lineWidth=poly.strokeWidth||2;ctx.setLineDash(poly.dashed?[7,5]:[]);ctx.stroke();ctx.restore()}}
function lab(s){return st.lang==='zh'?String(s).replace(/^Tower /,'高塔 '):String(s)}
function vis(m){if(m.icon==='tower')return document.getElementById('towerLayer')?.checked!==false;if(['lonestar','manticore','valkyra'].includes(m.icon))return document.getElementById('factionLayer')?.checked===true;if(['weapons_vendor','garage_vendor','spawn_board'].includes(m.icon))return document.getElementById('vendorLayer')?.checked===true;return false}
function render(){overlay.replaceChildren();const cam=2**q.zoom,k=Math.max(.14,1/Math.pow(cam,.38));for(const m of q.markers){if(!vis(m))continue;const wx=Number(m.x)/100,wy=Number(m.y)/100,p=w2s(wx,wy);if(p.x<-70||p.x>host.clientWidth+70||p.y<-70||p.y>host.clientHeight+70)continue;const tower=m.icon==='tower',el=document.createElement('div');el.className=tower?'v18-tower-marker':'v18-poi-marker';el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.setProperty('--k',k);const label=tower?lab(m.label):String(m.label||'').replace('Weapons Vendor','武器商人').replace('Garage Vendor','车库商人').replace('Spawn Board','部署板');el.innerHTML=`<img src="${ASSET}${ICON[m.icon]||ICON.tower}" alt=""><span>${label}</span>`;el.title=`${label} · X ${wx.toFixed(2)} / Y ${wy.toFixed(2)}`;el.onclick=e=>{if(!tower)return;e.stopPropagation();const c={x:wx,y:wy};if(!st.gunLocked){st.mode='gun';st.gun=c;sync();}focus(c)};overlay.appendChild(el)}for(const [kind,c] of [['gun',st.gun],['target',st.target]])if(c){const p=w2s(c.x,c.y),el=document.createElement('div');el.className=kind==='gun'?'v18-gun-point':'v18-target-point';el.style.left=p.x+'px';el.style.top=p.y+'px';overlay.appendChild(el)}}
function coordText(x,y){const e=document.getElementById('mapHoverCoord');if(!e||!Number.isFinite(x)||!Number.isFinite(y))return;const col=Math.min(15,Math.max(0,Math.floor((x%16+16)%16))),row=Math.min(15,Math.max(0,Math.floor((16-(y%16+16)%16))%16));e.textContent=`GRID ${String.fromCharCode(65+col)}${row+1} · X ${x.toFixed(2)} / Y ${y.toFixed(2)}`}
function hud(){const z=document.getElementById('hudZoom');if(z)z.textContent=`ZOOM ${2**q.zoom}×`;const h=document.getElementById('mapHud');if(h)h.textContent=q.loadOk?'高清地形已加载 · 1m/px 级细节':'正在加载高清地形…'}
function draw(){if(q.destroyed)return;cancelAnimationFrame(q.raf);q.raf=requestAnimationFrame(()=>{ctx.setTransform(q.dpr,0,0,q.dpr,0,0);ctx.fillStyle='#11171c';ctx.fillRect(0,0,host.clientWidth,host.clientHeight);drawTiles();drawPolys();drawGrid();render();hud();coordText(q.last?.x,q.last?.y);const b=document.getElementById('mapBrightness');if(b){canvas.style.filter=`brightness(${b.value}%)`;const v=document.getElementById('brightnessValue');if(v)v.textContent=b.value+'%'}})}
function sync(){const s=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v==null?'':Number(v).toFixed(2)};s('sx',st.gun?.x);s('sy',st.gun?.y);s('tx',st.target?.x);s('ty',st.target?.y);const g=document.getElementById('gunCoord'),t=document.getElementById('targetCoord');if(g)g.textContent=st.gun?`${st.gun.x.toFixed(2)}, ${st.gun.y.toFixed(2)}`:'--';if(t)t.textContent=st.target?`${st.target.x.toFixed(2)}, ${st.target.y.toFixed(2)}`:'--'}
function focus(c){q.zoom=Math.max(2,q.zoom);q.panX=0;q.panY=0;const v=view();q.panX=host.clientWidth/2-(v.left+(c.x-v.bounds.minX)*v.scale);q.panY=host.clientHeight/2-(v.top+(v.bounds.maxY-c.y)*v.scale);clampPan();draw()}
function setPoint(c){if(st.mode==='gun'){if(st.gunLocked)return;st.gun=c}else{if(st.targetLocked)return;st.target=c}sync();if(st.gun&&st.target)document.getElementById('calc')?.click();draw()}
function bind(){const on=(id,f)=>document.getElementById(id)?.addEventListener('click',f);on('zoomIn',()=>{q.zoom=Math.min(MAX_ZOOM,q.zoom+1);clampPan();draw()});on('zoomOut',()=>{q.zoom=Math.max(0,q.zoom-1);clampPan();draw()});on('fitMap',()=>{q.zoom=0;q.panX=q.panY=0;draw()});on('reload',()=>{for(const k of [...TILE_CACHE.keys()])if(String(k).startsWith(id+':'))TILE_CACHE.delete(k);q.loadOk=0;draw()});on('setGun',()=>st.mode='gun');on('setTarget',()=>st.mode='target');on('lockGun',()=>st.gunLocked=!st.gunLocked);on('lockTarget',()=>st.targetLocked=!st.targetLocked);on('clearGun',()=>{if(!st.gunLocked)st.gun=null;sync();draw()});on('clearTarget',()=>{if(!st.targetLocked)st.target=null;sync();draw()});on('resetMap',()=>{st.gun=null;st.target=null;st.gunLocked=false;st.targetLocked=false;q.zoom=0;q.panX=q.panY=0;sync();draw()});['towerLayer','factionLayer','vendorLayer','spawnLayer','gridLayer','mapBrightness'].forEach(id=>document.getElementById(id)?.addEventListener('input',draw));['towerLayer','factionLayer','vendorLayer','spawnLayer','gridLayer'].forEach(id=>document.getElementById(id)?.addEventListener('change',draw));tools.querySelector('[data-fit]')?.addEventListener('click',()=>document.getElementById('fitMap')?.click());tools.querySelector('[data-full]')?.addEventListener('click',async()=>{try{if(!document.fullscreenElement)await host.requestFullscreen?.();else await document.exitFullscreen?.()}catch{host.classList.toggle('v18-fullscreen')}})}
root.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;const r=root.getBoundingClientRect();q.ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});if(q.ptr.size===2){const a=[...q.ptr.values()];q.pinch={d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),z:q.zoom};q.drag=null;return}root.setPointerCapture?.(e.pointerId);q.drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:q.panX,py:q.panY};setCoord(e)});
root.addEventListener('pointermove',e=>{q.ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});setCoord(e);if(q.pinch&&q.ptr.size===2){const a=[...q.ptr.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);q.zoom=Math.max(0,Math.min(MAX_ZOOM,q.pinch.z+Math.log2(d/Math.max(1,q.pinch.d))));draw();return}if(q.drag?.id===e.pointerId){q.panX=q.drag.px+e.clientX-q.drag.x;q.panY=q.drag.py+e.clientY-q.drag.y;clampPan();draw()}});
root.addEventListener('pointerup',e=>{q.ptr.delete(e.pointerId);if(q.ptr.size<2)q.pinch=null;const d=q.drag;q.drag=null;if(d&&d.id===e.pointerId&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<6){const r=root.getBoundingClientRect();setPoint(s2w(e.clientX-r.left,e.clientY-r.top))}});root.addEventListener('pointercancel',e=>{q.ptr.delete(e.pointerId);q.drag=null;q.pinch=null});root.addEventListener('wheel',e=>{e.preventDefault();const r=root.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,b=s2w(mx,my);q.zoom=Math.max(0,Math.min(MAX_ZOOM,q.zoom+(e.deltaY<0?1:-1)));const v=view();const p=w2s(b.x,b.y);q.panX+=mx-p.x;q.panY+=my-p.y;clampPan();draw()},{passive:false});root.addEventListener('dblclick',e=>{e.preventDefault();const r=root.getBoundingClientRect(),c=s2w(e.clientX-r.left,e.clientY-r.top);q.zoom=Math.min(MAX_ZOOM,q.zoom+1);q.panX=q.panY=0;focus(c)});
function setCoord(e){const r=root.getBoundingClientRect(),c=s2w(e.clientX-r.left,e.clientY-r.top);if(c.x>=q.view.minX&&c.x<=q.view.maxX&&c.y>=q.view.minY&&c.y<=q.view.maxY){q.last=c;coordText(c.x,c.y)}}
const api={id,resize,resizeNow:resize,getZoom:()=>q.zoom,setView:focus,fitBounds:()=>{q.zoom=0;q.panX=q.panY=0;q.cx=(q.view.minX+q.view.maxX)/2;q.cy=(q.view.minY+q.view.maxY)/2;draw()},invalidateSize:resize,destroy:()=>{q.destroyed=true;cancelAnimationFrame(q.raf);overlay.replaceChildren();tools.remove();document.getElementById('v18-quick')?.remove()},setHud:v=>{const e=document.getElementById('mapHud');if(e)e.textContent=v},zoomIn:()=>{q.zoom=Math.min(MAX_ZOOM,q.zoom+1);draw()},zoomOut:()=>{q.zoom=Math.max(0,q.zoom-1);draw()}};
api.setData=data=>{q.data=data;q.view=data.bounds||{minX:0,maxX:163.84,minY:0,maxY:163.84};q.tile=data.tileBounds||{minX:0,maxX:163.84,minY:0,maxY:163.84};q.tiles=data.tiles||q.tiles;q.markers=data.markers||[];q.polygons=data.polygons||[];q.loadOk=0;q.zoom=0;q.panX=q.panY=0;cleanup();const box=document.createElement('div');box.id='v18-quick';box.className='v18-quick';box.innerHTML='<div class="v18-q-title">坐标快速定位</div><div class="v18-q-row"><input id="v18-coord" placeholder="例如 84.25, 62.10"><button id="v18-go">定位</button></div><div class="v18-q-title">高塔快速定位</div><div class="v18-q-row"><select id="v18-tower"><option value="">选择高塔</option></select><button id="v18-tgo">定位</button></div><div id="mapHoverCoord" class="v18-coord-readout">GRID -- · X -- / Y --</div>';host.parentElement.insertBefore(box,host);const sel=box.querySelector('#v18-tower');for(const m of q.markers.filter(x=>x.icon==='tower').sort((a,b)=>String(a.label).localeCompare(String(b.label),undefined,{numeric:true}))){const o=document.createElement('option');o.value=m.label;o.textContent=lab(m.label);sel.appendChild(o)}box.querySelector('#v18-go').onclick=()=>{const a=box.querySelector('#v18-coord').value.trim().split(/[,\s]+/).map(Number);if(a.length>=2&&a.every(Number.isFinite)&&a[0]>=q.view.minX&&a[0]<=q.view.maxX&&a[1]>=q.view.minY&&a[1]<=q.view.maxY){setPoint({x:a[0],y:a[1]});focus({x:a[0],y:a[1]})}};box.querySelector('#v18-tgo').onclick=()=>{const m=q.markers.find(x=>x.icon==='tower'&&x.label===sel.value);if(m){st.mode='gun';const c={x:Number(m.x)/100,y:Number(m.y)/100};if(!st.gunLocked){st.gun=c;sync()}focus(c)}};bind();resize();draw()};resize();return api}
boot();
})();
