(()=>{
'use strict';
const DATA='https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator/main/maps/';
const TILE_PROXY='/tiles/';
const ASSET='https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/';
const DEFAULT_TILE_SIZE=256,MAX_ZOOM=7,INITIAL_TILE_ZOOM=4,TILE_CACHE=new Map();
const ICON={tower:'assets/map-markers/tower.webp',lonestar:'assets/map-markers/lonestar.webp',manticore:'assets/map-markers/manticore.webp',valkyra:'assets/map-markers/valkyra.webp',weapons_vendor:'assets/map-markers/weapons_vendor.webp',garage_vendor:'assets/map-markers/garage_vendor.webp',spawn_board:'assets/map-markers/spawn_board.webp'};
function boot(){const s=window.Wardogs11,h=document.getElementById('map');if(!s||!h){setTimeout(boot,80);return}if(s.__mapV14)return;s.__mapV14=true;s.__mapV14Build=build;cleanupLegacy();setInterval(()=>{if(document.getElementById('page2')?.classList.contains('active'))cleanupLegacy()},500);document.getElementById('nav2')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();showPage(2);build()},true);document.getElementById('nav1')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();showPage(1)},true);document.getElementById('mapSelect')?.addEventListener('change',()=>build(true));const resize=()=>setTimeout(()=>s.canvasMap?.resize(),60);window.addEventListener('resize',resize,{passive:true});window.addEventListener('orientationchange',resize,{passive:true});setTimeout(()=>{if(document.getElementById('page2')?.classList.contains('active'))build()},80)}
function cleanupLegacy(){['towerQuick','coordQuick'].forEach(id=>document.getElementById(id)?.remove());document.querySelectorAll('.v11-quick,.v11-coord').forEach(e=>e.remove())}
function showPage(n){cleanupLegacy();document.getElementById('page1')?.classList.toggle('active',n===1);document.getElementById('page2')?.classList.toggle('active',n===2);document.getElementById('nav1')?.classList.toggle('active',n===1);document.getElementById('nav2')?.classList.toggle('active',n===2);if(n===2)setTimeout(()=>window.Wardogs11?.canvasMap?.resize(),40)}
async function loadConfig(id){const r=await fetch(DATA+id+'.json',{cache:'no-store'});if(!r.ok)throw Error('map config '+r.status);return r.json()}
function build(force=false){const s=window.Wardogs11,h=document.getElementById('map');if(!s||!h||!document.getElementById('page2')?.classList.contains('active')||!h.clientWidth||!h.clientHeight)return;cleanupLegacy();const id=document.getElementById('mapSelect')?.value||'bakurani';if(s.canvasMap?.id===id&&!force){s.canvasMap.resize();return}s.canvasMap?.destroy?.();h.replaceChildren();const hud=document.createElement('div');hud.className='v14-hud';hud.innerHTML='<span id="mapHud">加载 16K 高清地图…</span><span id="hudZoom">ZOOM 1×</span>';h.appendChild(hud);const m=createMap(h,id);s.canvasMap=m;loadConfig(id).then(d=>{if(s.canvasMap!==m)return;m.setData(d)}).catch(e=>{console.error(e);m.setHud('地图资料加载失败')})}
function createMap(host,id){const root=document.createElement('div');root.className='v14-map-root';const canvas=document.createElement('canvas');canvas.className='v14-map-canvas';const overlay=document.createElement('div');overlay.className='v14-marker-layer';const tools=document.createElement('div');tools.className='v14-map-tools';tools.innerHTML='<button type="button" data-tool="fit" aria-label="Fit map">⌂</button><button type="button" data-tool="full" aria-label="Fullscreen">⛶</button>';root.append(canvas,overlay,tools);host.appendChild(root);const ctx=canvas.getContext('2d',{alpha:false});const st=window.Wardogs11;const state={id,data:null,zoom:0,cx:81.92,cy:81.92,panX:0,panY:0,w:163.84,h:163.84,dpr:Math.max(1,Math.min(2,devicePixelRatio||1)),tileBounds:{minX:0,maxX:163.84,minY:0,maxY:163.84},tilePath:'',tiles:{tileSize:DEFAULT_TILE_SIZE,minZoom:0,maxZoom:MAX_ZOOM,extension:'webp'},markers:[],polygons:[],drag:null,pointers:new Map(),pinch:null,lastCoord:null,raf:0,destroyed:false,loadOk:0,failed:0};
function size(){const w=host.clientWidth,h=host.clientHeight;state.dpr=Math.max(1,Math.min(2,devicePixelRatio||1));canvas.width=Math.max(1,Math.round(w*state.dpr));canvas.height=Math.max(1,Math.round(h*state.dpr));canvas.style.width=w+'px';canvas.style.height=h+'px';draw()}
function scale(){const pad=8,fit=Math.min((host.clientWidth-pad*2)/Math.max(1,state.w),(host.clientHeight-pad*2)/Math.max(1,state.h));return fit*Math.pow(2,state.zoom)}
function w2s(x,y){const sc=scale();return{x:host.clientWidth/2+(x-state.cx)*sc+state.panX,y:host.clientHeight/2+(y-state.cy)*sc+state.panY}}
function s2w(x,y){const sc=scale();return{x:state.cx+(x-host.clientWidth/2-state.panX)/sc,y:state.cy+(y-host.clientHeight/2-state.panY)/sc}}
function clamp(){const sc=scale(),hw=host.clientWidth/(2*sc),hh=host.clientHeight/(2*sc);if(state.w*sc<=host.clientWidth)state.cx=(state.tileBounds.minX+state.tileBounds.maxX)/2;else state.cx=Math.max(state.tileBounds.minX+hw,Math.min(state.tileBounds.maxX-hw,state.cx));if(state.h*sc<=host.clientHeight)state.cy=(state.tileBounds.minY+state.tileBounds.maxY)/2;else state.cy=Math.max(state.tileBounds.minY+hh,Math.min(state.tileBounds.maxY-hh,state.cy))}
function tileZoom(){return Math.max(state.tiles.minZoom,Math.min(state.tiles.maxZoom,INITIAL_TILE_ZOOM+Math.floor(state.zoom)))}
function key(z,x,y){return `${state.id}:${z}:${x}:${y}`}
function tileUrl(z,x,y){return `${TILE_PROXY}${state.id}/zoom_${z}/${x}_${y}.${state.tiles.extension}`}
function loadTile(z,x,y){if(x<0||y<0||x>=2**z||y>=2**z)return null;const k=key(z,x,y);let t=TILE_CACHE.get(k);if(t)return t;t={img:new Image(),loaded:false,failed:false};TILE_CACHE.set(k,t);t.img.decoding='async';t.img.onload=()=>{t.loaded=true;state.loadOk++;draw()};t.img.onerror=()=>{t.failed=true;state.failed++;draw()};t.img.src=tileUrl(z,x,y);return t}
function ancestor(z,x,y){for(let a=z-1;a>=0;a--){const d=z-a,s=2**d,px=Math.floor(x/s),py=Math.floor(y/s),t=TILE_CACHE.get(key(a,px,py));if(t?.loaded&&!t.failed)return{t,sourceX:(x%s)*(DEFAULT_TILE_SIZE/s),sourceY:(y%s)*(DEFAULT_TILE_SIZE/s),sourceSize:DEFAULT_TILE_SIZE/s}}return null}
function drawTiles(){const z=tileZoom(),cnt=2**z,tw=(state.tileBounds.maxX-state.tileBounds.minX)/cnt,th=(state.tileBounds.maxY-state.tileBounds.minY)/cnt,sc=scale(),tl=s2w(0,0),br=s2w(host.clientWidth,host.clientHeight),left=Math.max(state.tileBounds.minX,Math.min(tl.x,br.x)-tw),right=Math.min(state.tileBounds.maxX,Math.max(tl.x,br.x)+tw),top=Math.max(state.tileBounds.minY,Math.min(tl.y,br.y)-th),bottom=Math.min(state.tileBounds.maxY,Math.max(tl.y,br.y)+th),minX=Math.max(0,Math.floor((left-state.tileBounds.minX)/tw)),maxX=Math.min(cnt-1,Math.floor((right-state.tileBounds.minX)/tw)),minY=Math.max(0,Math.floor((top-state.tileBounds.minY)/th)),maxY=Math.min(cnt-1,Math.floor((bottom-state.tileBounds.minY)/th));for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const t=loadTile(z,x,y),wx=state.tileBounds.minX+x*tw,wy=state.tileBounds.minY+y*th,p=w2s(wx,wy),sw=tw*sc+1,sh=th*sc+1;if(t?.loaded&&!t.failed)ctx.drawImage(t.img,p.x,p.y,sw,sh);else{const a=ancestor(z,x,y);if(a)ctx.drawImage(a.t.img,a.sourceX,a.sourceY,a.sourceSize,a.sourceSize,p.x,p.y,sw,sh);else{ctx.fillStyle='#10171e';ctx.fillRect(p.x,p.y,sw,sh)}}}}
function drawGrid(){if(document.getElementById('gridLayer')?.checked===false)return;ctx.strokeStyle='rgba(80,155,210,.24)';ctx.lineWidth=1;const cell=state.w/16;for(let i=0;i<=16;i++){const x=state.tileBounds.minX+i*cell,a=w2s(x,state.tileBounds.minY),b=w2s(x,state.tileBounds.maxY);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();const y=state.tileBounds.minY+i*cell,c=w2s(state.tileBounds.minX,y),d=w2s(state.tileBounds.maxX,y);ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.stroke()}}
function drawSpawnZones(){if(document.getElementById('spawnLayer')?.checked===false)return;for(const poly of state.polygons){const pts=poly.points||[];if(!pts.length)continue;ctx.beginPath();pts.forEach((q,i)=>{const p=w2s(q.x/100,q.y/100);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.closePath();ctx.fillStyle=poly.color||'#6fa9ce';ctx.globalAlpha=poly.fillOpacity??.12;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=poly.color||'#6fa9ce';ctx.lineWidth=2;ctx.setLineDash([7,5]);ctx.stroke();ctx.setLineDash([])}}
function towerLabel(v){return st.lang==='zh'?String(v).replace(/^Tower /,'高塔 '):String(v)}
function markerVisible(m){const tower=m.icon==='tower',faction=['lonestar','manticore','valkyra'].includes(m.icon),vendor=['weapons_vendor','garage_vendor','spawn_board'].includes(m.icon);if(tower)return document.getElementById('towerLayer')?.checked!==false;if(faction)return document.getElementById('factionLayer')?.checked===true;if(vendor)return document.getElementById('vendorLayer')?.checked===true;return false}
function iconUrl(icon){return ASSET+(ICON[icon]||ICON.tower)}
function renderMarkers(){overlay.replaceChildren();const z=state.zoom,cam=2**z;for(const m of state.markers){if(!markerVisible(m))continue;const p=w2s(Number(m.x)/100,Number(m.y)/100);if(p.x<-60||p.x>host.clientWidth+60||p.y<-60||p.y>host.clientHeight+60)continue;const el=document.createElement('div');const tower=m.icon==='tower';el.className=tower?'v14-tower-marker':'v14-poi-marker';const k=tower?Math.max(.14,1/Math.pow(cam,.42)):Math.max(.24,1/Math.pow(cam,.30));el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.setProperty('--k',k.toFixed(3));if(tower){el.innerHTML=`<img src="${iconUrl('tower')}" alt=""><span>${towerLabel(m.label)}</span>`;el.title=`${towerLabel(m.label)} · X ${(Number(m.x)/100).toFixed(2)} / Y ${(Number(m.y)/100).toFixed(2)}`;el.onclick=e=>{e.stopPropagation();const c={x:Number(m.x)/100,y:Number(m.y)/100};if(!st.gunLocked){st.mode='gun';st.gun={x:c.x,y:c.y}}syncInputs();focus(c)}}else{el.innerHTML=`<img src="${iconUrl(m.icon)}" alt=""><span>${String(m.label||'').replace('Weapons Vendor','武器商人').replace('Garage Vendor','车库商人').replace('Spawn Board','复活板')}</span>`}overlay.appendChild(el)}for(const [kind,c] of [['gun',st.gun],['target',st.target]])if(c){const p=w2s(c.x,c.y),el=document.createElement('div');el.className=kind==='gun'?'v14-gun-point':'v14-target-point';el.style.left=p.x+'px';el.style.top=p.y+'px';overlay.appendChild(el)}}
function updateCoord(x,y){const e=document.getElementById('mapHoverCoord');if(!e||!Number.isFinite(x)||!Number.isFinite(y))return;const col=Math.min(15,Math.max(0,Math.floor((x-state.tileBounds.minX)/(state.w/16)))),row=Math.min(15,Math.max(0,Math.floor((y-state.tileBounds.minY)/(state.h/16))));e.textContent=`GRID ${String.fromCharCode(65+col)}${row+1} · X ${x.toFixed(2)} / Y ${y.toFixed(2)}`}
function updateHud(){const z=document.getElementById('hudZoom');if(z)z.textContent='ZOOM '+(2**state.zoom).toFixed(0)+'×';const h=document.getElementById('mapHud');if(h)h.textContent=state.loadOk?'高清地图已加载 · 16K':'正在加载 16K 高清地图…'}
function draw(){if(state.destroyed)return;cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(()=>{ctx.setTransform(state.dpr,0,0,state.dpr,0,0);ctx.fillStyle='#10171e';ctx.fillRect(0,0,host.clientWidth,host.clientHeight);drawTiles();drawSpawnZones();drawGrid();renderMarkers();updateHud();updateCoord(state.lastCoord?.x,state.lastCoord?.y);const b=document.getElementById('mapBrightness');if(b){canvas.style.filter=`brightness(${b.value}%)`;const v=document.getElementById('brightnessValue');if(v)v.textContent=b.value+'%'}})}
function focus(c){state.cx=c.x;state.cy=c.y;state.panX=state.panY=0;clamp();draw()}
function syncInputs(){const set=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v==null?'':Number(v).toFixed(2)};set('sx',st.gun?.x);set('sy',st.gun?.y);set('tx',st.target?.x);set('ty',st.target?.y);const g=document.getElementById('gunCoord'),t=document.getElementById('targetCoord');if(g)g.textContent=st.gun?`${st.gun.x.toFixed(2)}, ${st.gun.y.toFixed(2)}`:'--';if(t)t.textContent=st.target?`${st.target.x.toFixed(2)}, ${st.target.y.toFixed(2)}`:'--'}
function setPoint(c){if(!Number.isFinite(c.x)||!Number.isFinite(c.y))return;if(st.mode==='gun'){if(st.gunLocked)return;st.gun={x:c.x,y:c.y}}else{if(st.targetLocked)return;st.target={x:c.x,y:c.y}}syncInputs();if(st.gun&&st.target)document.getElementById('calc')?.click();draw()}
function bind(){const on=(id,f)=>document.getElementById(id)?.addEventListener('click',f);on('zoomIn',()=>{state.zoom=Math.min(MAX_ZOOM,state.zoom+1);clamp();draw()});on('zoomOut',()=>{state.zoom=Math.max(0,state.zoom-1);clamp();draw()});on('fitMap',()=>{state.zoom=0;state.cx=(state.tileBounds.minX+state.tileBounds.maxX)/2;state.cy=(state.tileBounds.minY+state.tileBounds.maxY)/2;state.panX=state.panY=0;clamp();draw()});on('reload',()=>{for(const k of [...TILE_CACHE.keys()])if(String(k).startsWith(state.id+':'))TILE_CACHE.delete(k);state.loadOk=0;state.failed=0;draw()});on('setGun',()=>{st.mode='gun'});on('setTarget',()=>{st.mode='target'});on('lockGun',()=>{st.gunLocked=!st.gunLocked});on('lockTarget',()=>{st.targetLocked=!st.targetLocked});on('clearGun',()=>{if(!st.gunLocked)st.gun=null;syncInputs();draw()});on('clearTarget',()=>{if(!st.targetLocked)st.target=null;syncInputs();draw()});on('resetMap',()=>{st.gun=null;st.target=null;st.gunLocked=false;st.targetLocked=false;state.zoom=0;state.cx=(state.tileBounds.minX+state.tileBounds.maxX)/2;state.cy=(state.tileBounds.minY+state.tileBounds.maxY)/2;state.panX=state.panY=0;syncInputs();draw()});['towerLayer','factionLayer','vendorLayer','spawnLayer','gridLayer','mapBrightness'].forEach(id=>document.getElementById(id)?.addEventListener('input',draw));['towerLayer','factionLayer','vendorLayer','spawnLayer','gridLayer'].forEach(id=>document.getElementById(id)?.addEventListener('change',draw));tools.querySelector('[data-tool="fit"]')?.addEventListener('click',()=>document.getElementById('fitMap')?.click());tools.querySelector('[data-tool="full"]')?.addEventListener('click',async()=>{try{if(!document.fullscreenElement)await host.requestFullscreen?.();else await document.exitFullscreen?.()}catch{host.classList.toggle('v14-fullscreen')}})}
root.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;const r=root.getBoundingClientRect();state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size===2){const a=[...state.pointers.values()];state.pinch={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom:state.zoom};state.drag=null;return}root.setPointerCapture?.(e.pointerId);state.drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:state.panX,py:state.panY};setCoord(e)});
root.addEventListener('pointermove',e=>{state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});setCoord(e);if(state.pinch&&state.pointers.size===2){const a=[...state.pointers.values()];const dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),ratio=dist/Math.max(1,state.pinch.dist);state.zoom=Math.max(0,Math.min(MAX_ZOOM,state.pinch.zoom+Math.log2(ratio)));clamp();draw();return}if(!state.drag||state.drag.id!==e.pointerId)return;state.panX=state.drag.px+(e.clientX-state.drag.x);state.panY=state.drag.py+(e.clientY-state.drag.y);clamp();draw()});
root.addEventListener('pointerup',e=>{state.pointers.delete(e.pointerId);if(state.pointers.size<2)state.pinch=null;const d=state.drag;if(!d||d.id!==e.pointerId){state.drag=null;return}state.drag=null;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)<6){const r=root.getBoundingClientRect();setPoint(s2w(e.clientX-r.left,e.clientY-r.top))}});root.addEventListener('pointercancel',e=>{state.pointers.delete(e.pointerId);state.drag=null;state.pinch=null});root.addEventListener('wheel',e=>{e.preventDefault();const r=root.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,before=s2w(mx,my);state.zoom=Math.max(0,Math.min(MAX_ZOOM,state.zoom+(e.deltaY<0?1:-1)));const after=s2w(mx,my);state.cx+=before.x-after.x;state.cy+=before.y-after.y;clamp();draw()},{passive:false});root.addEventListener('dblclick',e=>{e.preventDefault();const r=root.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,c=s2w(mx,my);state.zoom=Math.min(MAX_ZOOM,state.zoom+1);state.cx=c.x;state.cy=c.y;clamp();draw()});function setCoord(e){const r=root.getBoundingClientRect(),c=s2w(e.clientX-r.left,e.clientY-r.top);if(c.x>=state.tileBounds.minX&&c.x<=state.tileBounds.maxX&&c.y>=state.tileBounds.minY&&c.y<=state.tileBounds.maxY){state.lastCoord=c;updateCoord(c.x,c.y)}}
const api={id,resize:size,resizeNow:size,getZoom:()=>state.zoom,setView:focus,fitBounds:()=>{state.zoom=0;state.cx=(state.tileBounds.minX+state.tileBounds.maxX)/2;state.cy=(state.tileBounds.minY+state.tileBounds.maxY)/2;state.panX=state.panY=0;clamp();draw()},invalidateSize:size,destroy:()=>{state.destroyed=true;cancelAnimationFrame(state.raf);overlay.replaceChildren();tools.remove();document.getElementById('v14-quick')?.remove()},setHud:v=>{const e=document.getElementById('mapHud');if(e)e.textContent=v},zoomIn:()=>{state.zoom=Math.min(MAX_ZOOM,state.zoom+1);clamp();draw()},zoomOut:()=>{state.zoom=Math.max(0,state.zoom-1);clamp();draw()}};
api.setData=data=>{state.data=data;state.tiles={tileSize:data.tiles?.tileSize||DEFAULT_TILE_SIZE,minZoom:data.tiles?.minZoom??0,maxZoom:data.tiles?.maxZoom??MAX_ZOOM,extension:data.tiles?.extension||'webp'};state.tileBounds=data.tileBounds||{minX:0,maxX:163.84,minY:0,maxY:163.84};state.w=state.tileBounds.maxX-state.tileBounds.minX;state.h=state.tileBounds.maxY-state.tileBounds.minY;state.cx=(state.tileBounds.minX+state.tileBounds.maxX)/2;state.cy=(state.tileBounds.minY+state.tileBounds.maxY)/2;state.markers=data.markers||[];state.polygons=data.polygons||[];cleanupLegacy();document.getElementById('v14-quick')?.remove();const q=document.createElement('div');q.id='v14-quick';q.className='v14-quick';q.innerHTML='<div class="v14-title">坐标快速定位</div><div class="v14-row"><input id="v14-coord" placeholder="例如 84.25, 62.10"><button id="v14-go">定位</button></div><div class="v14-title">高塔快速定位</div><div class="v14-row"><select id="v14-tower"><option value="">选择高塔</option></select><button id="v14-tgo">定位</button></div><div id="mapHoverCoord" class="v14-coord-readout">GRID -- · X -- / Y --</div>';host.parentElement.insertBefore(q,host);const ts=q.querySelector('#v14-tower');for(const m of state.markers.filter(x=>x.icon==='tower').sort((a,b)=>String(a.label).localeCompare(String(b.label),undefined,{numeric:true}))){const o=document.createElement('option');o.value=m.label;o.textContent=towerLabel(m.label);ts.appendChild(o)}q.querySelector('#v14-go').onclick=()=>{const a=(q.querySelector('#v14-coord').value||'').trim().split(/[,\s]+/).map(Number);if(a.length>=2&&a.every(Number.isFinite)){const c={x:a[0],y:a[1]};if(c.x>=state.tileBounds.minX&&c.x<=state.tileBounds.maxX&&c.y>=state.tileBounds.minY&&c.y<=state.tileBounds.maxY){setPoint(c);focus(c)}}};q.querySelector('#v14-tgo').onclick=()=>{const m=state.markers.find(x=>x.icon==='tower'&&x.label===ts.value);if(m){const c={x:Number(m.x)/100,y:Number(m.y)/100};setPoint(c);focus(c)}};bind();state.zoom=0;clamp();draw()};size();return api}
boot();
})();