(()=>{
'use strict';
const DATA='https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator/main/maps/';
const CDN='https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/maps/tiles/';
const TILE_PROXY='/tiles/';
const TOWER_ICON='https://cdn.jsdelivr.net/gh/apollyon-sys/wardogs-calculator@main/assets/map-markers/tower.webp';
const DEFAULT_TILE_SIZE=256,DEFAULT_WORLD=163.84,MAX_ZOOM=7,TILE_CACHE=new Map();
function boot(){const s=window.Wardogs11,h=document.getElementById('map');if(!s||!h){setTimeout(boot,80);return}if(s.__mapV14)return;s.__mapV14=true;s.__mapV14Build=build;cleanupLegacy();setInterval(()=>{if(document.getElementById('page2')?.classList.contains('active'))cleanupLegacy()},350);document.getElementById('nav2')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();showPage(2);build()},true);document.getElementById('nav1')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();showPage(1)},true);document.getElementById('mapSelect')?.addEventListener('change',()=>build(true));const resize=()=>setTimeout(()=>s.canvasMap?.resize(),60);window.addEventListener('resize',resize,{passive:true});window.addEventListener('orientationchange',resize,{passive:true});setTimeout(()=>{if(document.getElementById('page2')?.classList.contains('active'))build()},80)}
function cleanupLegacy(){['towerQuick','coordQuick'].forEach(id=>document.getElementById(id)?.remove());document.querySelectorAll('.v11-quick,.v11-coord').forEach(e=>e.remove())}
function showPage(n){cleanupLegacy();document.getElementById('page1')?.classList.toggle('active',n===1);document.getElementById('page2')?.classList.toggle('active',n===2);document.getElementById('nav1')?.classList.toggle('active',n===1);document.getElementById('nav2')?.classList.toggle('active',n===2);if(n===2)setTimeout(()=>window.Wardogs11?.canvasMap?.resize(),40)}
async function loadConfig(id){const r=await fetch(DATA+id+'.json',{cache:'no-store'});if(!r.ok)throw Error('map config '+r.status);return r.json()}
function build(force=false){const s=window.Wardogs11,h=document.getElementById('map');if(!s||!h||!document.getElementById('page2')?.classList.contains('active')||!h.clientWidth||!h.clientHeight)return;cleanupLegacy();const id=document.getElementById('mapSelect')?.value||'bakurani';if(s.canvasMap?.id===id&&!force){s.canvasMap.resize();return}s.canvasMap?.destroy?.();h.replaceChildren();const hud=document.createElement('div');hud.className='v14-hud';hud.innerHTML='<span id="mapHud">加载高清地图…</span><span id="hudZoom">ZOOM 1×</span>';h.appendChild(hud);const m=createMap(h,id);s.canvasMap=m;loadConfig(id).then(d=>{if(s.canvasMap!==m)return;m.setData(d)}).catch(e=>{console.error(e);m.setHud('地图资料加载失败')})}
function createMap(host,id){const root=document.createElement('div');root.className='v14-map-root';const canvas=document.createElement('canvas');canvas.className='v14-map-canvas';const overlay=document.createElement('div');overlay.className='v14-marker-layer';root.append(canvas,overlay);host.appendChild(root);const ctx=canvas.getContext('2d',{alpha:false});const st=window.Wardogs11;const state={id,data:null,zoom:0,cx:DEFAULT_WORLD/2,cy:DEFAULT_WORLD/2,panX:0,panY:0,w:DEFAULT_WORLD,h:DEFAULT_WORLD,dpr:Math.max(1,Math.min(2,devicePixelRatio||1)),tileBounds:{minX:0,maxX:DEFAULT_WORLD,minY:0,maxY:DEFAULT_WORLD},tilePath:'',tiles:{tileSize:DEFAULT_TILE_SIZE,minZoom:0,maxZoom:MAX_ZOOM,extension:'webp'},markers:[],polygons:[],drag:null,lastCoord:null,raf:0,destroyed:false,loadOk:0};
function size(){const w=host.clientWidth,h=host.clientHeight;state.dpr=Math.max(1,Math.min(2,devicePixelRatio||1));canvas.width=Math.max(1,Math.round(w*state.dpr));canvas.height=Math.max(1,Math.round(h*state.dpr));canvas.style.width=w+'px';canvas.style.height=h+'px';draw()}
function scale(){const pad=8,fit=Math.min((host.clientWidth-pad*2)/Math.max(1,state.w),(host.clientHeight-pad*2)/Math.max(1,state.h));return fit*Math.pow(2,state.zoom)}
function w2s(x,y){const sc=scale();return{x:host.clientWidth/2+(x-state.cx)*sc+state.panX,y:host.clientHeight/2+(state.cy-y)*sc+state.panY}}
function s2w(x,y){const sc=scale();return{x:state.cx+(x-host.clientWidth/2-state.panX)/sc,y:state.cy-(y-host.clientHeight/2-state.panY)/sc}}
function clamp(){const sc=scale(),hw=host.clientWidth/(2*sc),hh=host.clientHeight/(2*sc);state.cx=Math.max(state.tileBounds.minX+hw,Math.min(state.tileBounds.maxX-hw,state.cx));state.cy=Math.max(state.tileBounds.minY+hh,Math.min(state.tileBounds.maxY-hh,state.cy))}
function tileZoom(){return Math.max(state.tiles.minZoom,Math.min(state.tiles.maxZoom,state.zoom))}
function key(z,x,y){return `${state.id}:${z}:${x}:${y}`}
function tileUrls(z,x,y){const p=state.tilePath;const a=[`${TILE_PROXY}${state.id}/zoom_${z}/${x}_${y}.${state.tiles.extension}`];if(p)a.push(`${p}/zoom_${z}/${x}_${y}.${state.tiles.extension}`);a.push(`${CDN}${state.id}/zoom_${z}/${x}_${y}.${state.tiles.extension}`);return [...new Set(a)]}
function loadTile(z,x,y){if(x<0||y<0||x>=2**z||y>=2**z)return null;const k=key(z,x,y);let t=TILE_CACHE.get(k);if(t)return t;t={img:new Image(),loaded:false,failed:false,i:0,urls:tileUrls(z,x,y)};TILE_CACHE.set(k,t);const next=()=>{if(t.i>=t.urls.length){t.failed=true;draw();return}const u=t.urls[t.i++];t.img=new Image();t.img.onload=()=>{t.loaded=true;state.loadOk++;draw()};t.img.onerror=next;t.img.decoding='async';t.img.src=u};next();return t}
function ancestor(z,x,y){for(let a=z-1;a>=0;a--){const d=z-a,s=2**d,px=Math.floor(x/s),py=Math.floor(y/s),t=TILE_CACHE.get(key(a,px,py));if(t?.loaded&&!t.failed)return{t,sourceX:(x%s)*(DEFAULT_TILE_SIZE/s),sourceY:(y%s)*(DEFAULT_TILE_SIZE/s),sourceSize:DEFAULT_TILE_SIZE/s}}return null}
function drawTiles(){const z=tileZoom(),cnt=2**z,tw=(state.tileBounds.maxX-state.tileBounds.minX)/cnt,th=(state.tileBounds.maxY-state.tileBounds.minY)/cnt,sc=scale(),tl=s2w(0,0),br=s2w(host.clientWidth,host.clientHeight),left=Math.max(state.tileBounds.minX,Math.min(tl.x,br.x)-tw),right=Math.min(state.tileBounds.maxX,Math.max(tl.x,br.x)+tw),top=Math.min(state.tileBounds.maxY,Math.max(tl.y,br.y)+th),bottom=Math.max(state.tileBounds.minY,Math.min(tl.y,br.y)-th),minX=Math.max(0,Math.floor((left-state.tileBounds.minX)/tw)),maxX=Math.min(cnt-1,Math.floor((right-state.tileBounds.minX)/tw)),minY=Math.max(0,Math.floor((state.tileBounds.maxY-top)/th)),maxY=Math.min(cnt-1,Math.floor((state.tileBounds.maxY-bottom)/th));for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const t=loadTile(z,x,y),wx=state.tileBounds.minX+x*tw,wy=state.tileBounds.maxY-y*th,p=w2s(wx,wy),sw=tw*sc+1,sh=th*sc+1;if(t?.loaded&&!t.failed)ctx.drawImage(t.img,p.x,p.y,sw,sh);else{const a=ancestor(z,x,y);if(a)ctx.drawImage(a.t.img,a.sourceX,a.sourceY,a.sourceSize,a.sourceSize,p.x,p.y,sw,sh);else{ctx.fillStyle='#11181e';ctx.fillRect(p.x,p.y,sw,sh)}}}}
function drawOverlays(){if(document.getElementById('gridLayer')?.checked!==false){ctx.strokeStyle='rgba(100,170,225,.2)';ctx.lineWidth=1;for(let i=0;i<=16;i++){const p=i*DEFAULT_WORLD/16,a=w2s(p,0),b=w2s(p,DEFAULT_WORLD),c=w2s(0,p),d=w2s(DEFAULT_WORLD,p);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.stroke()}}if(document.getElementById('battleLayer')?.checked!==false)for(const poly of state.polygons){const pts=poly.points||[];if(!pts.length)continue;ctx.beginPath();pts.forEach((q,i)=>{const p=w2s(q.x/100,q.y/100);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.closePath();ctx.fillStyle=poly.color||'#6fa9ce';ctx.globalAlpha=poly.fillOpacity??.12;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=poly.color||'#6fa9ce';ctx.setLineDash([7,5]);ctx.stroke();ctx.setLineDash([])}}
function towerLabel(v){return st.lang==='zh'?String(v).replace(/^Tower /,'高塔 '):String(v)}
function renderMarkers(){overlay.replaceChildren();const z=state.zoom;for(const m of state.markers){const tower=m.icon==='tower',show=tower?(document.getElementById('towerLayer')?.checked!==false):(document.getElementById('facilityLayer')?.checked===true);if(!show)continue;const p=w2s(m.x/100,(DEFAULT_WORLD*100-m.y)/100);if(p.x<-40||p.x>host.clientWidth+40||p.y<-40||p.y>host.clientHeight+40)continue;const el=document.createElement('div');el.className=tower?'v14-tower-marker':'v14-poi-marker';const k=tower?Math.max(.20,1/(1+z*.48)):Math.max(.30,1/(1+z*.26));el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.setProperty('--k',k.toFixed(3));if(tower){const label=z>=2?`<span>${towerLabel(m.label)}</span>`:'';el.innerHTML=`<img src="${TOWER_ICON}" alt="">${label}`;el.title=m.label||'';el.onclick=e=>{e.stopPropagation();const c={x:m.x/100,y:(DEFAULT_WORLD*100-m.y)/100};setPoint(c);focus(c)}}else{el.textContent=String(m.label||'').replace('Weapons Vendor','武器商人').replace('Garage Vendor','车库商人').replace('Spawn Board','复活板')}overlay.appendChild(el)}for(const [kind,c] of [['gun',st.gun],['target',st.target]])if(c){const p=w2s(c.x,c.y),el=document.createElement('div');el.className=kind==='gun'?'v14-gun-point':'v14-target-point';el.style.left=p.x+'px';el.style.top=p.y+'px';overlay.appendChild(el)}}
function updateCoord(x,y){const e=document.getElementById('mapHoverCoord');if(!e)return;if(Number.isFinite(x)&&Number.isFinite(y)){const col=Math.min(15,Math.max(0,Math.floor(x/(DEFAULT_WORLD/16)))),row=Math.min(16,Math.max(1,Math.floor(y/(DEFAULT_WORLD/16))+1));e.textContent=`GRID ${String.fromCharCode(65+col)}${row} · X ${x.toFixed(2)} / Y ${y.toFixed(2)}`}}
function updateHud(){const z=document.getElementById('hudZoom');if(z)z.textContent='ZOOM '+(2**state.zoom).toFixed(0)+'×';const h=document.getElementById('mapHud');if(h)h.textContent=state.loadOk?'高清地图已加载':'正在加载高清地图…'}
function draw(){if(state.destroyed)return;cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(()=>{ctx.setTransform(state.dpr,0,0,state.dpr,0,0);ctx.fillStyle='#11181e';ctx.fillRect(0,0,host.clientWidth,host.clientHeight);drawTiles();drawOverlays();renderMarkers();updateHud();updateCoord(state.lastCoord?.x,state.lastCoord?.y)})}
function focus(c){state.cx=c.x;state.cy=c.y;state.panX=state.panY=0;clamp();draw()}
function setPoint(c){if(st.mode==='gun'){if(st.gunLocked)return;st.gun={x:c.x,y:c.y}}else{if(st.targetLocked)return;st.target={x:c.x,y:c.y}};syncInputs();if(st.gun&&st.target)document.getElementById('calc')?.click();draw()}
function syncInputs(){const set=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v==null?'':Number(v).toFixed(2)};set('sx',st.gun?.x);set('sy',st.gun?.y);set('tx',st.target?.x);set('ty',st.target?.y);const g=document.getElementById('gunCoord'),t=document.getElementById('targetCoord');if(g)g.textContent=st.gun?`${st.gun.x.toFixed(2)}, ${st.gun.y.toFixed(2)}`:'--';if(t)t.textContent=st.target?`${st.target.x.toFixed(2)}, ${st.target.y.toFixed(2)}`:'--'}
function bind(){const on=(id,f)=>document.getElementById(id)?.addEventListener('click',f);on('zoomIn',()=>{state.zoom=Math.min(MAX_ZOOM,state.zoom+1);clamp();draw()});on('zoomOut',()=>{state.zoom=Math.max(0,state.zoom-1);clamp();draw()});on('reload',()=>{for(const k of TILE_CACHE.keys())if(String(k).startsWith(state.id+':'))TILE_CACHE.delete(k);state.loadOk=0;draw()});on('setGun',()=>{st.mode='gun'});on('setTarget',()=>{st.mode='target'});on('lockGun',()=>{st.gunLocked=!st.gunLocked});on('lockTarget',()=>{st.targetLocked=!st.targetLocked});on('clearGun',()=>{if(!st.gunLocked)st.gun=null;syncInputs();draw()});on('clearTarget',()=>{if(!st.targetLocked)st.target=null;syncInputs();draw()});on('resetMap',()=>{st.gun=null;st.target=null;st.gunLocked=false;st.targetLocked=false;state.zoom=0;state.cx=DEFAULT_WORLD/2;state.cy=DEFAULT_WORLD/2;state.panX=state.panY=0;syncInputs();draw()});['towerLayer','facilityLayer','battleLayer','gridLayer'].forEach(id=>document.getElementById(id)?.addEventListener('change',draw))}
root.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;root.setPointerCapture?.(e.pointerId);state.drag={id:e.pointerId,x:e.clientX,y:e.clientY,px:state.panX,py:state.panY};setCoord(e)});root.addEventListener('pointermove',e=>{setCoord(e);if(!state.drag||state.drag.id!==e.pointerId)return;state.panX=state.drag.px+(e.clientX-state.drag.x);state.panY=state.drag.py+(e.clientY-state.drag.y);clamp();draw()});root.addEventListener('pointerup',e=>{const d=state.drag;if(!d)return;state.drag=null;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)<6)setPoint(s2w(e.clientX-root.getBoundingClientRect().left,e.clientY-root.getBoundingClientRect().top))});root.addEventListener('pointercancel',()=>state.drag=null);root.addEventListener('wheel',e=>{e.preventDefault();const r=root.getBoundingClientRect(),before=s2w(e.clientX-r.left,e.clientY-r.top);state.zoom=Math.max(0,Math.min(MAX_ZOOM,state.zoom+(e.deltaY<0?1:-1)));const after=s2w(e.clientX-r.left,e.clientY-r.top);state.cx+=before.x-after.x;state.cy+=before.y-after.y;clamp();draw()},{passive:false});function setCoord(e){const r=root.getBoundingClientRect(),c=s2w(e.clientX-r.left,e.clientY-r.top);if(c.x>=state.tileBounds.minX&&c.x<=state.tileBounds.maxX&&c.y>=state.tileBounds.minY&&c.y<=state.tileBounds.maxY){state.lastCoord=c;updateCoord(c.x,c.y)}}
const api={id,resize:size,resizeNow:size,getZoom:()=>state.zoom,setView:focus,fitBounds:()=>{state.zoom=0;state.cx=DEFAULT_WORLD/2;state.cy=DEFAULT_WORLD/2;state.panX=state.panY=0;draw()},invalidateSize:size,destroy:()=>{state.destroyed=true;cancelAnimationFrame(state.raf);overlay.replaceChildren();document.getElementById('v14-quick')?.remove()},setHud:v=>{const e=document.getElementById('mapHud');if(e)e.textContent=v}};api.zoomIn=()=>{state.zoom=Math.min(MAX_ZOOM,state.zoom+1);clamp();draw()};api.zoomOut=()=>{state.zoom=Math.max(0,state.zoom-1);clamp();draw()};api.setData=data=>{state.data=data;state.tilePath=String(data.tiles?.path||'').replace(/\/$/,'');state.tiles={tileSize:data.tiles?.tileSize||DEFAULT_TILE_SIZE,minZoom:data.tiles?.minZoom??0,maxZoom:data.tiles?.maxZoom??MAX_ZOOM,extension:data.tiles?.extension||'webp'};state.tileBounds=data.tileBounds||{minX:0,maxX:DEFAULT_WORLD,minY:0,maxY:DEFAULT_WORLD};state.w=state.tileBounds.maxX-state.tileBounds.minX;state.h=state.tileBounds.maxY-state.tileBounds.minY;state.cx=(state.tileBounds.minX+state.tileBounds.maxX)/2;state.cy=(state.tileBounds.minY+state.tileBounds.maxY)/2;state.markers=data.markers||[];state.polygons=data.polygons||[];cleanupLegacy();const q=document.createElement('div');q.id='v14-quick';q.className='v14-quick';q.innerHTML='<div class="v14-title">坐标快速定位</div><div class="v14-row"><input id="v14-coord" placeholder="例如 84.25, 62.10"><button id="v14-go">定位</button></div><div class="v14-title">高塔快速定位</div><div class="v14-row"><select id="v14-tower"><option value="">选择高塔</option></select><button id="v14-tgo">定位</button></div><div id="mapHoverCoord" class="v14-coord-readout">GRID -- · X -- / Y --</div>';host.parentElement.insertBefore(q,host);const ts=q.querySelector('#v14-tower');for(const m of state.markers.filter(x=>x.icon==='tower').sort((a,b)=>String(a.label).localeCompare(String(b.label),undefined,{numeric:true}))){const o=document.createElement('option');o.value=m.label;o.textContent=towerLabel(m.label);ts.appendChild(o)}q.querySelector('#v14-go').onclick=()=>{const a=(q.querySelector('#v14-coord').value||'').trim().split(/[,\s]+/).map(Number);if(a.length>=2&&a.every(Number.isFinite)){const c={x:a[0],y:a[1]};if(c.x>=0&&c.x<=DEFAULT_WORLD&&c.y>=0&&c.y<=DEFAULT_WORLD){setPoint(c);focus(c)}}};q.querySelector('#v14-tgo').onclick=()=>{const m=state.markers.find(x=>x.icon==='tower'&&x.label===ts.value);if(m){const c={x:m.x/100,y:(DEFAULT_WORLD*100-m.y)/100};setPoint(c);focus(c)}};bind();state.zoom=0;state.cx=(state.tileBounds.minX+state.tileBounds.maxX)/2;state.cy=(state.tileBounds.minY+state.tileBounds.maxY)/2;state.panX=state.panY=0;clamp();draw()};size();return api}
boot();
})();