const { chromium } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const cp = require('node:child_process');
const URL='https://wardogs-field-assistant2.cloudsoo2004.workers.dev/';
const ROOT='https://raw.githubusercontent.com/apollyon-sys/wardogs-calculator/main/';
function browserPath(){for(const p of ['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'])if(fs.existsSync(p))return p;return cp.execFileSync('which',['google-chrome'],{encoding:'utf8'}).trim()}
(async()=>{
 fs.mkdirSync('test-artifacts',{recursive:true});
 const browser=await chromium.launch({headless:true,executablePath:browserPath(),args:['--disable-dev-shm-usage']});
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1'});
 const page=await context.newPage();page.setDefaultTimeout(20000);const errors=[],tiles=[];page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.url().includes('/tiles/'))tiles.push({url:r.url(),status:r.status()})});
 const index=await (await context.request.get(ROOT+'maps/index.json')).json();assert.ok(Array.isArray(index)&&index.length>=3,'map registry must expose current map files');
 for(const entry of index){const id=String(entry).replace(/\.json$/,'');const r=await context.request.get(ROOT+'maps/'+id+'.json');assert.equal(r.status(),200,`map config ${id} must be reachable`);const d=await r.json();assert.ok(d.bounds&&d.tileBounds&&d.tiles&&d.tiles.maxZoom>=7,`${id} bounds/zoom invalid`);assert.equal(d.coordinateMetersPerUnit,100,`${id} coordinate scale invalid`);assert.ok(Array.isArray(d.markers),`${id} markers missing`)}
 const bak=await (await context.request.get(ROOT+'maps/bakurani.json')).json();const oz=await (await context.request.get(ROOT+'maps/ozeti.json')).json();const bakT=bak.markers.filter(m=>m.icon==='tower'),ozT=oz.markers.filter(m=>m.icon==='tower');assert.equal(bakT.length,5);assert.equal(ozT.length,4);
 const ozV=oz.markers.find(m=>m.icon==='valkyra');assert.ok(ozV);assert.deepEqual([Number(ozV.x)/100,Number(ozV.y)/100],[118.75,70.93]);
 const bakCoords=Object.fromEntries(bakT.map(m=>[m.label,[Number(m.x)/100,Number(m.y)/100]]));assert.deepEqual(bakCoords['Tower 1'],[80.52,69.85]);assert.deepEqual(bakCoords['Tower 5'],[82.22,68.41]);
 await page.goto(URL,{waitUntil:'domcontentloaded'});assert.match(await page.locator('#sub').textContent(),/第 1 页/);assert.equal(await page.locator('#lang').textContent(),'EN');
 await page.locator('#lang').click();await page.waitForFunction(()=>document.getElementById('sub')?.textContent?.includes('PAGE 1'));assert.equal(await page.locator('#lang').textContent(),'中文');await page.locator('#lang').click();await page.waitForFunction(()=>document.getElementById('sub')?.textContent?.includes('第 1 页'));assert.equal(await page.locator('#lang').textContent(),'EN');
 await page.locator('#nav2').click();await page.waitForFunction(()=>window.Wardogs19?.map?.id==='bakurani');await page.waitForSelector('canvas.v22-canvas');await page.waitForSelector('.v22-tower');await page.waitForTimeout(1000);assert.ok(tiles.some(x=>x.status===200),'terrain tiles must load');assert.equal(await page.locator('#v22-quick').count(),1);assert.equal(await page.locator('.v11-quick,.v11-coord,.v14-quick,.v18-quick,.v19-quick,.v20-quick,.v21-quick').count(),0);assert.equal(await page.locator('.v22-tower').count(),5);
 const rendered=await page.locator('.v22-tower').evaluateAll(es=>es.map(e=>({label:e.dataset.label,x:Number(e.dataset.x),y:Number(e.dataset.y)})));for(const [label,xy] of Object.entries(bakCoords)){const got=rendered.find(v=>v.label===label);assert.ok(got,`missing ${label}`);assert.deepEqual([got.x,got.y],xy,`wrong ${label}`)}
 await page.locator('#setTarget').click();assert.equal(await page.locator('#setTarget').evaluate(e=>e.classList.contains('active')),true);await page.locator('#towerSelect').selectOption('Tower 5');await page.locator('#towerGo').click();await page.waitForFunction(()=>Math.abs(window.Wardogs19.gun?.x-82.22)<.001&&Math.abs(window.Wardogs19.gun?.y-68.41)<.001);assert.equal(await page.locator('#setTarget').evaluate(e=>e.classList.contains('active')),true,'tower quick must only set gun');
 await page.locator('#setGun').click();await page.locator('#v22-x').fill('84.25');await page.locator('#v22-y').fill('62.10');await page.locator('#coordGo').click();await page.waitForFunction(()=>Math.abs(window.Wardogs19.gun?.x-84.25)<.001&&Math.abs(window.Wardogs19.gun?.y-62.10)<.001);
 await page.locator('#setTarget').click();await page.locator('#v22-x').fill('88.40');await page.locator('#v22-y').fill('66.20');await page.locator('#coordGo').click();await page.waitForFunction(()=>Math.abs(window.Wardogs19.target?.x-88.40)<.001&&Math.abs(window.Wardogs19.target?.y-66.20)<.001);
 await page.locator('#fitMap').click();await page.waitForFunction(()=>window.Wardogs19.map?.getZoom?.()===0);const before=await page.locator('.v22-tower').first().locator('img').boundingBox();assert.ok(before&&before.width>=25,'tower icon too small at fit');await page.locator('#zoomIn').click();await page.locator('#zoomIn').click();await page.waitForFunction(()=>window.Wardogs19.map?.getZoom?.()===2);const after=await page.locator('.v22-tower').first().locator('img').boundingBox();assert.ok(after&&after.width>=22,'tower icon too small at 4x');assert.ok(after.width<before.width,'tower icon should still shrink at 4x');
 await page.locator('#factionLayer').check();await page.waitForSelector('.v22-poi[data-label="Valkyra"]');const v=await page.locator('.v22-poi[data-label="Valkyra"]').evaluate(e=>({x:Number(e.dataset.x),y:Number(e.dataset.y)}));assert.deepEqual(v,{x:118.75,y:70.93});await page.locator('#vendorLayer').check();await page.locator('#spawnLayer').check();assert.ok(await page.locator('.v22-poi').count()>=6);await page.locator('#inactiveTowerLayer').check();assert.equal(await page.locator('#inactiveTowerLayer').isChecked(),true);
 await page.locator('#mapSelect').selectOption('zestafona');await page.waitForFunction(()=>window.Wardogs19.map?.id==='zestafona');await page.waitForSelector('.v22-tower');assert.equal(await page.locator('.v22-tower').count(),3);await page.locator('#mapSelect').selectOption('bakurani');await page.waitForFunction(()=>window.Wardogs19.map?.id==='bakurani');
 await page.locator('#lang').click();await page.waitForFunction(()=>document.getElementById('nav2')?.textContent?.includes('PAGE 2'));assert.equal(await page.locator('#v22-quick').count(),1);assert.match(await page.locator('#towerQuickTitle').textContent(),/TOWER QUICK LOCATION/);assert.doesNotMatch(await page.locator('#v22-quick').textContent(),/高塔快速定位/);await page.locator('#lang').click();await page.waitForFunction(()=>document.getElementById('nav2')?.textContent?.includes('第 2 页'));assert.equal(await page.locator('#v22-quick').count(),1);assert.match(await page.locator('#towerQuickTitle').textContent(),/高塔快速定位/);
 await page.screenshot({path:'test-artifacts/v22-final.png',fullPage:false});assert.deepEqual(errors,[],'browser page errors were reported');console.log('LIVE E2E PASS: one-click language, no duplicate quick UI, exact tower coordinates, tower-only gun quick location, separate XY jump, 4x tower sizing, exact OZETI faction point, inactive layer, dynamic map registry, Zestafona load');await context.close();await browser.close();
})().catch(err=>{console.error(err.stack||err);process.exit(1)});
